export const DATA = [
  {
    "id": "adeptCanoness",
    "name": "Roswitha",
    "title": "Canoness",
    "fullName": "Roswitha Esther",
    "shortName": "Roswitha",
    "extraShortName": "Roswitha",
    "factionId": "Sisterhood",
    "alliance": "Imperial",
    "health": 85,
    "damage": 30,
    "armour": 17,
    "initialRarity": "Uncommon",
    "meleeDamage": "Chain",
    "meleeHits": 3,
    "rangedDamage": "Bolter",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "ActOfFaith"
    ],
    "activeAbility": [
      "Flame"
    ],
    "passiveAbility": [],
    "number": 9,
    "icon": "snowprint_assets/characters/ui_image_portrait_adept_canoness_01.png",
    "roundIcon": "ui_image_RoundPortrait_adept_canoness_01.png"
  },
  {
    "id": "adeptCelestine",
    "name": "Celestine",
    "title": "Living Saint",
    "fullName": "Celestine, the living Saint",
    "shortName": "Celestine",
    "extraShortName": "Celestine",
    "factionId": "Sisterhood",
    "alliance": "Imperial",
    "health": 60,
    "damage": 25,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ActOfFaith",
      "Flying"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 10,
    "icon": "snowprint_assets/characters/ui_image_portrait_adept_celestine_01.png",
    "roundIcon": "ui_image_RoundPortrait_adept_celestine_01.png"
  },
  {
    "id": "adeptHospitaller",
    "name": "Isabella",
    "title": "Hospitaller",
    "fullName": "Isabella Mariken",
    "shortName": "Isabella",
    "extraShortName": "Isabella",
    "factionId": "Sisterhood",
    "alliance": "Imperial",
    "health": 85,
    "damage": 20,
    "armour": 18,
    "initialRarity": "Rare",
    "meleeDamage": "Bolter",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "ActOfFaith",
      "Healer"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 7,
    "icon": "snowprint_assets/characters/ui_image_portrait_adept_hospitaller_01.png",
    "roundIcon": "ui_image_RoundPortrait_adept_hospitaller_01.png"
  },
  {
    "id": "adeptMorvenn",
    "name": "Morvenn Vahl",
    "title": "Abbess Sanctorum of the Adepta Sororitas",
    "fullName": "Morvenn Vahl",
    "shortName": "Morvenn Vahl",
    "extraShortName": "Morvenn Vahl",
    "factionId": "Sisterhood",
    "alliance": "Imperial",
    "health": 95,
    "damage": 24,
    "armour": 24,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 2,
    "rangedDamage": "Bolter",
    "rangedHits": 3,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "ActOfFaith",
      "BigTarget",
      "Explodes",
      "Mechanical"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [
      "Power"
    ],
    "number": 8,
    "icon": "snowprint_assets/characters/ui_image_portrait_adept_morvenn_01.png",
    "roundIcon": "ui_image_RoundPortrait_adept_morvenn_01.png"
  },
  {
    "id": "adeptRetributor",
    "name": "Vindicta",
    "title": "Celestian",
    "fullName": "Battle Sister Vindicta",
    "shortName": "Vindicta",
    "extraShortName": "Vindicta",
    "factionId": "Sisterhood",
    "alliance": "Imperial",
    "health": 70,
    "damage": 20,
    "armour": 12,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Flame",
    "rangedHits": 4,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ActOfFaith",
      "HeavyWeapon"
    ],
    "activeAbility": [
      "Flame"
    ],
    "passiveAbility": [
      "Flame"
    ],
    "number": 6,
    "icon": "snowprint_assets/characters/ui_image_portrait_adept_retributor_01.png",
    "roundIcon": "ui_image_RoundPortrait_adept_retributor_01.png"
  },
  {
    "id": "admecDestroyer",
    "name": "Sy-gex",
    "title": "Kataphron Destroyer",
    "fullName": "Sy-gex-KPH008/15.mk41",
    "shortName": "Sy-gex",
    "extraShortName": "Sy-gex",
    "factionId": "AdeptusMechanicus",
    "alliance": "Imperial",
    "health": 95,
    "damage": 25,
    "armour": 17,
    "initialRarity": "Uncommon",
    "meleeDamage": "Flame",
    "meleeHits": 4,
    "rangedDamage": "Physical",
    "rangedHits": 4,
    "distance": 3,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Mechanical",
      "HeavyWeapon",
      "Overwatch",
      "Vehicle"
    ],
    "activeAbility": [
      "Physical"
    ],
    "passiveAbility": [],
    "number": 79,
    "icon": "snowprint_assets/characters/ui_image_portrait_admec_destroyer_01.png",
    "roundIcon": "ui_image_RoundPortrait_admec_destroyer_01.png"
  },
  {
    "id": "admecDominus",
    "name": "Vitruvius",
    "title": "Tech-Priest Dominus",
    "fullName": "Magos Dominus Vitruvius Thannek",
    "shortName": "Vitruvius",
    "extraShortName": "Vitruvius",
    "factionId": "AdeptusMechanicus",
    "alliance": "Imperial",
    "health": 90,
    "damage": 50,
    "armour": 18,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 1,
    "rangedDamage": "Gauss",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Mechanical",
      "Mechanic"
    ],
    "activeAbility": [
      "Toxic"
    ],
    "passiveAbility": [],
    "number": 75,
    "icon": "snowprint_assets/characters/ui_image_portrait_admec_dominus_01.png",
    "roundIcon": "ui_image_RoundPortrait_admec_dominus_01.png"
  },
  {
    "id": "admecManipulus",
    "name": "Actus",
    "title": "Tech-Priest Manipulus",
    "fullName": "Manipulus Actus Fulgorosus",
    "shortName": "Actus",
    "extraShortName": "Actus",
    "factionId": "AdeptusMechanicus",
    "alliance": "Imperial",
    "health": 95,
    "damage": 25,
    "armour": 19,
    "initialRarity": "Rare",
    "meleeDamage": "Energy",
    "meleeHits": 2,
    "rangedDamage": "Energy",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Mechanical",
      "Mechanic",
      "Flying"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 76,
    "icon": "snowprint_assets/characters/ui_image_portrait_admec_manipulus_01.png",
    "roundIcon": "ui_image_RoundPortrait_admec_manipulus_01.png"
  },
  {
    "id": "admecMarshall",
    "name": "Tan Gi'da",
    "title": "Skitarii Marshal",
    "fullName": "Tan Gi'da",
    "shortName": "Tan Gi'da",
    "extraShortName": "Tan Gi'da",
    "factionId": "AdeptusMechanicus",
    "alliance": "Imperial",
    "health": 85,
    "damage": 35,
    "armour": 16,
    "initialRarity": "Rare",
    "meleeDamage": "Physical",
    "meleeHits": 2,
    "rangedDamage": "Toxic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Mechanical"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 77,
    "icon": "snowprint_assets/characters/ui_image_portrait_admec_marshall_01.png",
    "roundIcon": "ui_image_RoundPortrait_admec_marshall_01.png"
  },
  {
    "id": "admecRuststalker",
    "name": "Exitor-Rho",
    "title": "Sicarian Ruststalker Princeps",
    "fullName": "Exitor-Rho-1.15/x",
    "shortName": "Exitor-Rho",
    "extraShortName": "Exitor-Rho",
    "factionId": "AdeptusMechanicus",
    "alliance": "Imperial",
    "health": 80,
    "damage": 30,
    "armour": 17,
    "initialRarity": "Uncommon",
    "meleeDamage": "Energy",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Mechanical",
      "Camouflage",
      "Infiltrate",
      "Unstoppable"
    ],
    "activeAbility": [
      "DirectDamage"
    ],
    "passiveAbility": [
      "Energy"
    ],
    "number": 78,
    "icon": "snowprint_assets/characters/ui_image_portrait_admec_ruststalker_01.png",
    "roundIcon": "ui_image_RoundPortrait_admec_ruststalker_01.png"
  },
  {
    "id": "astraBullgryn",
    "name": "Kut",
    "title": "Bullgryn Bone’ead",
    "fullName": "Kut Skoden",
    "shortName": "Kut Skoden",
    "extraShortName": "Kut",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 95,
    "damage": 30,
    "armour": 35,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Defensive",
    "traits": [
      "BigTarget"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [],
    "number": 22,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_bullgryn_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_bullgryn_01.png"
  },
  {
    "id": "astraCreed",
    "name": "Creed",
    "title": "Lord General of the Astra Militarum",
    "fullName": "Lord Castellan Ursarkar E. Creed",
    "shortName": "Castellan Creed",
    "extraShortName": "Creed",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 90,
    "damage": 38,
    "armour": 21,
    "initialRarity": "Legendary",
    "meleeDamage": "Las",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 26,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_creed_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_creed_01.png"
  },
  {
    "id": "astraDreir",
    "name": "Dreir",
    "title": "Lord Marshal",
    "fullName": "Lord Marshal Varnan Dreir",
    "shortName": "Marshal Dreir",
    "extraShortName": "Dreir",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 100,
    "damage": 28,
    "armour": 17,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Resilient",
      "Unstoppable"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [],
    "number": 113,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_dreir_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_dreir_01.png"
  },
  {
    "id": "astraOrdnance",
    "name": "Thaddeus",
    "title": "Master of Ordnance",
    "fullName": "Thaddeus Noble",
    "shortName": "Thaddeus Noble",
    "extraShortName": "Thaddeus",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 65,
    "damage": 38,
    "armour": 15,
    "initialRarity": "Rare",
    "meleeDamage": "Las",
    "meleeHits": 1,
    "rangedDamage": "Blast",
    "rangedHits": 3,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "SuppressiveFire",
      "IndirectFire"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [],
    "number": 24,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_ordnance_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_ordnance_01.png"
  },
  {
    "id": "astraPrimarisPsy",
    "name": "Sibyll",
    "title": "Primaris Psyker",
    "fullName": "Sibyll Devine",
    "shortName": "Sibyll Devine",
    "extraShortName": "Sibyll",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 55,
    "damage": 30,
    "armour": 20,
    "initialRarity": "Common",
    "meleeDamage": "Psychic",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Psyker"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 23,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_psyker_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_psyker_01.png"
  },
  {
    "id": "astraYarrick",
    "name": "Yarrick",
    "title": "Lord Commissar",
    "fullName": "Commissar Sebastian Yarrick",
    "shortName": "Commissar Yarrick",
    "extraShortName": "Yarrick",
    "factionId": "AstraMilitarum",
    "alliance": "Imperial",
    "health": 75,
    "damage": 30,
    "armour": 17,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": "Bolter",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Resilient"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 25,
    "icon": "snowprint_assets/characters/ui_image_portrait_astra_yarrick_01.png",
    "roundIcon": "ui_image_RoundPortrait_astra_yarrick_01.png"
  },
  {
    "id": "blackAbaddon",
    "name": "Abaddon",
    "title": "Warmaster of Chaos",
    "fullName": "Abaddon the Despoiler",
    "shortName": "Abaddon the Despoiler",
    "extraShortName": "Abaddon",
    "factionId": "BlackLegion",
    "alliance": "Chaos",
    "health": 100,
    "damage": 15,
    "armour": 25,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 5,
    "rangedDamage": "Bolter",
    "rangedHits": 3,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "LetTheGalaxyBurn",
      "Resilient",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 20,
    "icon": "snowprint_assets/characters/ui_image_portrait_black_abaddon_01.png",
    "roundIcon": "ui_image_RoundPortrait_black_abaddon_01.png"
  },
  {
    "id": "blackHaarken",
    "name": "Haarken",
    "title": "Herald of the Apocalypse",
    "fullName": "Haarken Worldclaimer",
    "shortName": "Haarken Worldclaimer",
    "extraShortName": "Haarken",
    "factionId": "BlackLegion",
    "alliance": "Chaos",
    "health": 95,
    "damage": 11,
    "armour": 20,
    "initialRarity": "Epic",
    "meleeDamage": "Piercing",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LetTheGalaxyBurn",
      "Flying",
      "Terrifying"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 19,
    "icon": "snowprint_assets/characters/ui_image_portrait_black_haarken_01.png",
    "roundIcon": "ui_image_RoundPortrait_black_haarken_01.png"
  },
  {
    "id": "blackObliterator",
    "name": "Volk",
    "title": "Obliterator",
    "fullName": "Volk, Reforged by the Warp",
    "shortName": "Volk",
    "extraShortName": "Volk",
    "factionId": "BlackLegion",
    "alliance": "Chaos",
    "health": 125,
    "damage": 9,
    "armour": 12,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": "HeavyRound",
    "rangedHits": 6,
    "distance": 3,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LetTheGalaxyBurn",
      "BigTarget",
      "Daemon",
      "HeavyWeapon",
      "SuppressiveFire"
    ],
    "activeAbility": [
      "HeavyRound"
    ],
    "passiveAbility": [
      "Flame",
      "HeavyRound",
      "Melta"
    ],
    "number": 17,
    "icon": "snowprint_assets/characters/ui_image_portrait_black_obliterator_01.png",
    "roundIcon": "ui_image_RoundPortrait_black_obliterator_01.png"
  },
  {
    "id": "blackPossession",
    "name": "Archimatos",
    "title": "Master of Possession",
    "fullName": "Master Archimatos",
    "shortName": "Archimatos",
    "extraShortName": "Archimatos",
    "factionId": "BlackLegion",
    "alliance": "Chaos",
    "health": 80,
    "damage": 16,
    "armour": 18,
    "initialRarity": "Uncommon",
    "meleeDamage": "Psychic",
    "meleeHits": 2,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LetTheGalaxyBurn",
      "Psyker"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 18,
    "icon": "snowprint_assets/characters/ui_image_portrait_black_possession_01.png",
    "roundIcon": "ui_image_RoundPortrait_black_possession_01.png"
  },
  {
    "id": "blackTerminator",
    "name": "Angrax",
    "title": "Terminator Champion",
    "fullName": "Drakfus Angrax",
    "shortName": "Angrax",
    "extraShortName": "Angrax",
    "factionId": "BlackLegion",
    "alliance": "Chaos",
    "health": 110,
    "damage": 19,
    "armour": 30,
    "initialRarity": "Common",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "LetTheGalaxyBurn",
      "TeleportStrike",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [],
    "number": 16,
    "icon": "snowprint_assets/characters/ui_image_portrait_black_terminator_01.png",
    "roundIcon": "ui_image_RoundPortrait_black_terminator_01.png"
  },
  {
    "id": "bloodDante",
    "name": "Dante",
    "title": "Chapter Master",
    "fullName": "Commander Dante",
    "shortName": "Dante",
    "extraShortName": "Dante",
    "factionId": "BloodAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 11,
    "armour": 23,
    "initialRarity": "Legendary",
    "meleeDamage": "Piercing",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "TeleportStrike",
      "FinalJustice",
      "Flying",
      "RapidAssault",
      "Terrifying"
    ],
    "activeAbility": [
      "Melta"
    ],
    "passiveAbility": [],
    "number": 101,
    "icon": "snowprint_assets/characters/ui_image_portrait_blood_dante_01.png",
    "roundIcon": "ui_image_RoundPortrait_blood_dante_01.png"
  },
  {
    "id": "bloodDeathCompany",
    "name": "Lucien",
    "title": "Death Company Intercessor",
    "fullName": "Lucien",
    "shortName": "Lucien",
    "extraShortName": "Lucien",
    "factionId": "BloodAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 30,
    "armour": 21,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 4,
    "rangedDamage": "Blast",
    "rangedHits": 3,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "RapidAssault",
      "Resilient",
      "Unstoppable"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Bolter"
    ],
    "number": 89,
    "icon": "snowprint_assets/characters/ui_image_portrait_blood_deathcompany_01.png",
    "roundIcon": "ui_image_RoundPortrait_blood_deathcompany_01.png"
  },
  {
    "id": "bloodIntercessor",
    "name": "Mataneo",
    "title": "Jump Pack Intercessor Sergeant",
    "fullName": "Mataneo",
    "shortName": "Mataneo",
    "extraShortName": "Mataneo",
    "factionId": "BloodAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 40,
    "armour": 22,
    "initialRarity": "Uncommon",
    "meleeDamage": "Plasma",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "TeleportStrike",
      "Flying",
      "RapidAssault"
    ],
    "activeAbility": [
      "Physical",
      "Power"
    ],
    "passiveAbility": [],
    "number": 72,
    "icon": "snowprint_assets/characters/ui_image_portrait_blood_intercessor_01.png",
    "roundIcon": "ui_image_RoundPortrait_blood_intercessor_01.png"
  },
  {
    "id": "bloodMephiston",
    "name": "Mephiston",
    "title": "Lord of Death",
    "fullName": "Mephiston",
    "shortName": "Mephiston",
    "extraShortName": "Mephiston",
    "factionId": "BloodAngels",
    "alliance": "Imperial",
    "health": 95,
    "damage": 10,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Psychic",
    "meleeHits": 3,
    "rangedDamage": "Psychic",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Psyker",
      "RapidAssault",
      "Terrifying"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Psychic"
    ],
    "number": 73,
    "icon": "snowprint_assets/characters/ui_image_portrait_blood_mephiston_01.png",
    "roundIcon": "ui_image_RoundPortrait_blood_mephiston_01.png"
  },
  {
    "id": "bloodSanguinary",
    "name": "Nicodemus",
    "title": "Sanguinary Priest",
    "fullName": "Nicodemus",
    "shortName": "Nicodemus",
    "extraShortName": "Nicodemus",
    "factionId": "BloodAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 23,
    "armour": 23,
    "initialRarity": "Rare",
    "meleeDamage": "Chain",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Healer",
      "RapidAssault"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 99,
    "icon": "snowprint_assets/characters/ui_image_portrait_blood_sanguinary_01.png",
    "roundIcon": "ui_image_RoundPortrait_blood_sanguinary_01.png"
  },
  {
    "id": "custoAtlacoya",
    "name": "Atlacoya",
    "title": "Vigilator",
    "fullName": "Atlacoya",
    "shortName": "Atlacoya",
    "extraShortName": "Atlacoya",
    "factionId": "Custodes",
    "alliance": "Imperial",
    "health": 80,
    "damage": 30,
    "armour": 19,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Parry",
      "Terrifying"
    ],
    "activeAbility": [
      "DirectDamage",
      "Power"
    ],
    "passiveAbility": [],
    "number": 110,
    "icon": "snowprint_assets/characters/ui_image_portrait_custo_atlacoya_01.png",
    "roundIcon": "ui_image_RoundPortrait_custo_atlacoya_01.png"
  },
  {
    "id": "custoBladeChampion",
    "name": "Kariyan",
    "title": "Blade Champion",
    "fullName": "Kariyan Helsates",
    "shortName": "Kariyan",
    "extraShortName": "Kariyan",
    "factionId": "Custodes",
    "alliance": "Imperial",
    "health": 95,
    "damage": 21,
    "armour": 24,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "MartialKatah",
      "BeastSnagga",
      "RapidAssault",
      "Parry",
      "Resilient"
    ],
    "activeAbility": [
      "Eviscerate"
    ],
    "passiveAbility": [
      "Piercing",
      "Power"
    ],
    "number": 107,
    "icon": "snowprint_assets/characters/ui_image_portrait_custo_bladechampion_01.png",
    "roundIcon": "ui_image_RoundPortrait_custo_bladechampion_01.png"
  },
  {
    "id": "custoKyrus",
    "name": "Tyrith",
    "title": "Custodian Guard",
    "fullName": "Tyrith Shiva Kyrus",
    "shortName": "Tyrith",
    "extraShortName": "Tyrith",
    "factionId": "Custodes",
    "alliance": "Imperial",
    "health": 95,
    "damage": 25,
    "armour": 22,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": "Bolter",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "MartialKatah",
      "Resilient"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [
      "Bolter"
    ],
    "number": 118,
    "icon": "snowprint_assets/characters/ui_image_portrait_custo_kyrus_01.png",
    "roundIcon": "ui_image_RoundPortrait_custo_kyrus_01.png"
  },
  {
    "id": "custoTrajann",
    "name": "Trajann",
    "title": "Captain-General",
    "fullName": "Trajann Valoris",
    "shortName": "Trajann",
    "extraShortName": "Trajann",
    "factionId": "Custodes",
    "alliance": "Imperial",
    "health": 100,
    "damage": 11,
    "armour": 25,
    "initialRarity": "Legendary",
    "meleeDamage": "Piercing",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "MartialKatah",
      "CrushingStrike",
      "Resilient"
    ],
    "activeAbility": [
      "Bolter"
    ],
    "passiveAbility": [],
    "number": 105,
    "icon": "snowprint_assets/characters/ui_image_portrait_custo_trajann_01.png",
    "roundIcon": "ui_image_RoundPortrait_custo_trajann_01.png"
  },
  {
    "id": "custoVexilusPraetor",
    "name": "Aesoth",
    "title": "Vexilus Praetor",
    "fullName": "Aesoth Koumadra",
    "shortName": "Aesoth",
    "extraShortName": "Aesoth",
    "factionId": "Custodes",
    "alliance": "Imperial",
    "health": 110,
    "damage": 58,
    "armour": 28,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "MartialKatah",
      "BigTarget",
      "Resilient"
    ],
    "activeAbility": [
      "Physical"
    ],
    "passiveAbility": [],
    "number": 106,
    "icon": "snowprint_assets/characters/ui_image_portrait_custo_vexilus_01.png",
    "roundIcon": "ui_image_RoundPortrait_custo_vexilus_01.png"
  },
  {
    "id": "darkaAsmodai",
    "name": "Asmodai",
    "title": "Master of Repentance",
    "fullName": "Asmodai",
    "shortName": "Asmodai",
    "extraShortName": "Asmodai",
    "factionId": "DarkAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 20,
    "armour": 23,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Terrifying"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 60,
    "icon": "snowprint_assets/characters/ui_image_portrait_darka_asmodai_01.png",
    "roundIcon": "ui_image_RoundPortrait_darka_asmodai_01.png"
  },
  {
    "id": "darkaAzrael",
    "name": "Azrael",
    "title": "Supreme Grandmaster",
    "fullName": "Azrael",
    "shortName": "Azrael",
    "extraShortName": "Azrael",
    "factionId": "DarkAngels",
    "alliance": "Imperial",
    "health": 95,
    "damage": 28,
    "armour": 24,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": "Plasma",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "FinalJustice",
      "Overwatch"
    ],
    "activeAbility": [
      "Bolter",
      "DirectDamage"
    ],
    "passiveAbility": [],
    "number": 58,
    "icon": "snowprint_assets/characters/ui_image_portrait_darka_azrael_01.png",
    "roundIcon": "ui_image_RoundPortrait_darka_azrael_01.png"
  },
  {
    "id": "darkaCompanion",
    "name": "Forcas",
    "title": "Inner Circle Companion",
    "fullName": "Forcas Oathsworn",
    "shortName": "Forcas",
    "extraShortName": "Forcas",
    "factionId": "DarkAngels",
    "alliance": "Imperial",
    "health": 90,
    "damage": 12,
    "armour": 21,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 6,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Camouflage",
      "Parry"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [],
    "number": 104,
    "icon": "snowprint_assets/characters/ui_image_portrait_darka_companion_01.png",
    "roundIcon": "ui_image_RoundPortrait_darka_companion_01.png"
  },
  {
    "id": "darkaHellblaster",
    "name": "Sarquael",
    "title": "Hellblaster Sergeant",
    "fullName": "Sarquael",
    "shortName": "Sarquael",
    "extraShortName": "Sarquael",
    "factionId": "DarkAngels",
    "alliance": "Imperial",
    "health": 70,
    "damage": 50,
    "armour": 20,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Plasma",
    "rangedHits": 1,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "FinalJustice",
      "Overwatch",
      "HeavyWeapon"
    ],
    "activeAbility": [
      "Plasma"
    ],
    "passiveAbility": [
      "Plasma"
    ],
    "number": 61,
    "icon": "snowprint_assets/characters/ui_image_portrait_darka_hellblaster_01.png",
    "roundIcon": "ui_image_RoundPortrait_darka_hellblaster_01.png"
  },
  {
    "id": "darkaTerminator",
    "name": "Baraqiel",
    "title": "Deathwing Terminator",
    "fullName": "Baraqiel",
    "shortName": "Baraqiel",
    "extraShortName": "Baraqiel",
    "factionId": "DarkAngels",
    "alliance": "Imperial",
    "health": 110,
    "damage": 22,
    "armour": 29,
    "initialRarity": "Uncommon",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "TeleportStrike",
      "CrushingStrike",
      "HeavyWeapon",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "Plasma"
    ],
    "passiveAbility": [],
    "number": 59,
    "icon": "snowprint_assets/characters/ui_image_portrait_darka_terminator_01.png",
    "roundIcon": "ui_image_RoundPortrait_darka_terminator_01.png"
  },
  {
    "id": "deathBlightbringer",
    "name": "Corrodius",
    "title": "Noxious Blightbringer",
    "fullName": "Corrodius Achebile",
    "shortName": "Corrodius",
    "extraShortName": "Corrodius",
    "factionId": "DeathGuard",
    "alliance": "Chaos",
    "health": 125,
    "damage": 40,
    "armour": 25,
    "initialRarity": "Rare",
    "meleeDamage": "Plasma",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ContagionsOfNurgle",
      "Resilient"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 30,
    "icon": "snowprint_assets/characters/ui_image_portrait_death_blightbringer_01.png",
    "roundIcon": "ui_image_RoundPortrait_death_blightbringer_01.png"
  },
  {
    "id": "deathBlightlord",
    "name": "Maladus",
    "title": "Blightlord Champion",
    "fullName": "Maladus Phlegmore",
    "shortName": "Maladus",
    "extraShortName": "Maladus",
    "factionId": "DeathGuard",
    "alliance": "Chaos",
    "health": 120,
    "damage": 26,
    "armour": 33,
    "initialRarity": "Uncommon",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "ContagionsOfNurgle",
      "Resilient",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [
      "Toxic"
    ],
    "number": 29,
    "icon": "snowprint_assets/characters/ui_image_portrait_death_blightlord_01.png",
    "roundIcon": "ui_image_RoundPortrait_death_blightlord_01.png"
  },
  {
    "id": "deathPutrifier",
    "name": "Pestillian",
    "title": "Biologus Putrifier",
    "fullName": "Pestillian Witherpus",
    "shortName": "Pestillian",
    "extraShortName": "Pestillian",
    "factionId": "DeathGuard",
    "alliance": "Chaos",
    "health": 120,
    "damage": 40,
    "armour": 27,
    "initialRarity": "Rare",
    "meleeDamage": "Toxic",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ContagionsOfNurgle",
      "Resilient",
      "PutridExplosion"
    ],
    "activeAbility": [
      "Toxic"
    ],
    "passiveAbility": [],
    "number": 31,
    "icon": "snowprint_assets/characters/ui_image_portrait_death_putrifier_01.png",
    "roundIcon": "ui_image_RoundPortrait_death_putrifier_01.png"
  },
  {
    "id": "deathRotbone",
    "name": "Nauseous",
    "title": "Plague Surgeon",
    "fullName": "Nauseous Rotbone",
    "shortName": "Nauseous Rotbone",
    "extraShortName": "Nauseous",
    "factionId": "DeathGuard",
    "alliance": "Chaos",
    "health": 120,
    "damage": 14,
    "armour": 27,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ContagionsOfNurgle",
      "Resilient",
      "Healer"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 32,
    "icon": "snowprint_assets/characters/ui_image_portrait_death_rotbone_01.png",
    "roundIcon": "ui_image_RoundPortrait_death_rotbone_01.png"
  },
  {
    "id": "deathTyphus",
    "name": "Typhus",
    "title": "Herald of the Plague God",
    "fullName": "Typhus, Host of the Destroyer Hive",
    "shortName": "Typhus",
    "extraShortName": "Typhus",
    "factionId": "DeathGuard",
    "alliance": "Chaos",
    "health": 120,
    "damage": 18,
    "armour": 25,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "ContagionsOfNurgle",
      "Resilient",
      "Psyker",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [
      "DirectDamage"
    ],
    "number": 28,
    "icon": "snowprint_assets/characters/ui_image_portrait_death_typhus_01.png",
    "roundIcon": "ui_image_RoundPortrait_death_typhus_01.png"
  },
  {
    "id": "eldarAutarch",
    "name": "Aethana",
    "title": "Autarch",
    "fullName": "Aethana Barantharal",
    "shortName": "Aethana",
    "extraShortName": "Aethana",
    "factionId": "Aeldari",
    "alliance": "Xenos",
    "health": 80,
    "damage": 14,
    "armour": 17,
    "initialRarity": "Uncommon",
    "meleeDamage": "Piercing",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 5,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Flying",
      "TeleportStrike"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 44,
    "icon": "snowprint_assets/characters/ui_image_portrait_aelda_autarch_01.png",
    "roundIcon": "ui_image_RoundPortrait_aelda_autarch_01.png"
  },
  {
    "id": "eldarFarseer",
    "name": "Eldryon",
    "title": "Farseer",
    "fullName": "Eldryon Ynaduin",
    "shortName": "Eldryon",
    "extraShortName": "Eldryon",
    "factionId": "Aeldari",
    "alliance": "Xenos",
    "health": 75,
    "damage": 16,
    "armour": 16,
    "initialRarity": "Rare",
    "meleeDamage": "Piercing",
    "meleeHits": 2,
    "rangedDamage": "Psychic",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Psyker"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 46,
    "icon": "snowprint_assets/characters/ui_image_portrait_aelda_farseer_01.png",
    "roundIcon": "ui_image_RoundPortrait_aelda_farseer_01.png"
  },
  {
    "id": "eldarJainZar",
    "name": "Jain Zar",
    "title": "Howling Banshee Phoenix Lord",
    "fullName": "Jain Zar",
    "shortName": "Jain Zar",
    "extraShortName": "Jain Zar",
    "factionId": "Aeldari",
    "alliance": "Xenos",
    "health": 75,
    "damage": 19,
    "armour": 18,
    "initialRarity": "Legendary",
    "meleeDamage": "Piercing",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Infiltrate"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 47,
    "icon": "snowprint_assets/characters/ui_image_portrait_aelda_jainzar_01.png",
    "roundIcon": "ui_image_RoundPortrait_aelda_jainzar_01.png"
  },
  {
    "id": "eldarMauganRa",
    "name": "Maugan Ra",
    "title": "Dark Reaper Phoenix Lord",
    "fullName": "Maugan Ra",
    "shortName": "Maugan Ra",
    "extraShortName": "Maugan Ra",
    "factionId": "Aeldari",
    "alliance": "Xenos",
    "health": 70,
    "damage": 9,
    "armour": 22,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 5,
    "rangedDamage": "HeavyRound",
    "rangedHits": 6,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Terrifying",
      "HeavyWeapon",
      "Overwatch"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 45,
    "icon": "snowprint_assets/characters/ui_image_portrait_aelda_maugan_01.png",
    "roundIcon": "ui_image_RoundPortrait_aelda_maugan_01.png"
  },
  {
    "id": "eldarRanger",
    "name": "Calandis",
    "title": "Ranger",
    "fullName": "Calandis Tawaren",
    "shortName": "Calandis",
    "extraShortName": "Calandis",
    "factionId": "Aeldari",
    "alliance": "Xenos",
    "health": 70,
    "damage": 45,
    "armour": 18,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Energy",
    "rangedHits": 1,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Crit",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "HeavyWeapon",
      "Overwatch"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Piercing"
    ],
    "number": 43,
    "icon": "snowprint_assets/characters/ui_image_portrait_aelda_ranger_01.png",
    "roundIcon": "ui_image_RoundPortrait_aelda_ranger_01.png"
  },
  {
    "id": "emperExultant",
    "name": "Laviscus",
    "title": "Lord Exultant",
    "fullName": "Laviscus Sentrillion, the Perfect",
    "shortName": "Laviscus",
    "extraShortName": "Laviscus",
    "factionId": "EmperorsChildren",
    "alliance": "Chaos",
    "health": 90,
    "damage": 40,
    "armour": 21,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ThrillSeekers",
      "CrushingStrike"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [],
    "number": 123,
    "icon": "snowprint_assets/characters/ui_image_portrait_emper_exultant_01.png",
    "roundIcon": "ui_image_RoundPortrait_emper_exultant_01.png"
  },
  {
    "id": "emperFlawlessBlade",
    "name": "Hascule",
    "title": "Flawless Blade",
    "fullName": "Hascule Thorn of the Silken Blade",
    "shortName": "Hascule",
    "extraShortName": "Hascule",
    "factionId": "EmperorsChildren",
    "alliance": "Chaos",
    "health": 95,
    "damage": 15,
    "armour": 19,
    "initialRarity": "Rare",
    "meleeDamage": "Piercing",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ThrillSeekers",
      "Parry"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Eviscerate"
    ],
    "number": 120,
    "icon": "snowprint_assets/characters/ui_image_portrait_emper_blade_01.png",
    "roundIcon": "ui_image_RoundPortrait_emper_blade_01.png"
  },
  {
    "id": "emperKakophonist",
    "name": "Adamatar",
    "title": "Lord Kakophonist",
    "fullName": "Adamatar Xandassus, Mirrorborn",
    "shortName": "Adamatar",
    "extraShortName": "Adamatar",
    "factionId": "EmperorsChildren",
    "alliance": "Chaos",
    "health": 100,
    "damage": 17,
    "armour": 23,
    "initialRarity": "Rare",
    "meleeDamage": "Eviscerate",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ThrillSeekers"
    ],
    "activeAbility": [
      "DirectDamage"
    ],
    "passiveAbility": [],
    "number": 115,
    "icon": "snowprint_assets/characters/ui_image_portrait_emper_kakophonist_01.png",
    "roundIcon": "ui_image_RoundPortrait_emper_kakophonist_01.png"
  },
  {
    "id": "emperLucius",
    "name": "Lucius",
    "title": "Champion of Slaanesh",
    "fullName": "Lucius the Eternal",
    "shortName": "Lucius",
    "extraShortName": "Lucius",
    "factionId": "EmperorsChildren",
    "alliance": "Chaos",
    "health": 90,
    "damage": 13,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 6,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ThrillSeekers",
      "Parry"
    ],
    "activeAbility": [
      "Eviscerate"
    ],
    "passiveAbility": [],
    "number": 111,
    "icon": "snowprint_assets/characters/ui_image_portrait_emper_lucius_01.png",
    "roundIcon": "ui_image_RoundPortrait_emper_lucius_01.png"
  },
  {
    "id": "emperNoiseMarine",
    "name": "Shiron",
    "title": "Noise Marine",
    "fullName": "Shiron Capersi, the Idolator",
    "shortName": "Shiron",
    "extraShortName": "Shiron",
    "factionId": "EmperorsChildren",
    "alliance": "Chaos",
    "health": 85,
    "damage": 6,
    "armour": 20,
    "initialRarity": "Uncommon",
    "meleeDamage": "Eviscerate",
    "meleeHits": 3,
    "rangedDamage": "Eviscerate",
    "rangedHits": 6,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "ThrillSeekers",
      "HeavyWeapon",
      "SuppressiveFire"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [],
    "number": 112,
    "icon": "snowprint_assets/characters/ui_image_portrait_emper_noisemarine_01.png",
    "roundIcon": "ui_image_RoundPortrait_emper_noisemarine_01.png"
  },
  {
    "id": "genesBiophagus",
    "name": "Hollan",
    "title": "Biophagus",
    "fullName": "Hollan Baumgart",
    "shortName": "Hollan",
    "extraShortName": "Hollan",
    "factionId": "Genestealers",
    "alliance": "Xenos",
    "health": 55,
    "damage": 36,
    "armour": 12,
    "initialRarity": "Uncommon",
    "meleeDamage": "Toxic",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Ambush",
      "Healer"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 96,
    "icon": "snowprint_assets/characters/ui_image_portrait_genes_biophagus_01.png",
    "roundIcon": "ui_image_RoundPortrait_genes_biophagus_01.png"
  },
  {
    "id": "genesKelermorph",
    "name": "Judh",
    "title": "Kelermorph",
    "fullName": "Judh Lhaska",
    "shortName": "Judh",
    "extraShortName": "Judh",
    "factionId": "Genestealers",
    "alliance": "Xenos",
    "health": 60,
    "damage": 25,
    "armour": 13,
    "initialRarity": "Epic",
    "meleeDamage": "Projectile",
    "meleeHits": 3,
    "rangedDamage": "Projectile",
    "rangedHits": 3,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Crit",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Ambush",
      "BeastSnagga"
    ],
    "activeAbility": [
      "Projectile"
    ],
    "passiveAbility": [
      "Projectile"
    ],
    "number": 100,
    "icon": "snowprint_assets/characters/ui_image_portrait_genes_kelermorph_01.png",
    "roundIcon": "ui_image_RoundPortrait_genes_kelermorph_01.png"
  },
  {
    "id": "genesMagus",
    "name": "Xybia",
    "title": "Magus",
    "fullName": "Xybia Kheiser",
    "shortName": "Xybia",
    "extraShortName": "Xybia",
    "factionId": "Genestealers",
    "alliance": "Xenos",
    "health": 55,
    "damage": 15,
    "armour": 11,
    "initialRarity": "Rare",
    "meleeDamage": "Psychic",
    "meleeHits": 2,
    "rangedDamage": "Psychic",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Ambush",
      "Psyker"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 92,
    "icon": "snowprint_assets/characters/ui_image_portrait_genes_magus_01.png",
    "roundIcon": "ui_image_RoundPortrait_genes_magus_01.png"
  },
  {
    "id": "genesPatriarch",
    "name": "The Patermine",
    "title": "Genestealer Patriarch",
    "fullName": "The Patermine",
    "shortName": "The Patermine",
    "extraShortName": "The Patermine",
    "factionId": "Genestealers",
    "alliance": "Xenos",
    "health": 100,
    "damage": 14,
    "armour": 17,
    "initialRarity": "Legendary",
    "meleeDamage": "Eviscerate",
    "meleeHits": 5,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Infiltrate",
      "Synapse",
      "Terrifying",
      "Unstoppable"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 94,
    "icon": "snowprint_assets/characters/ui_image_portrait_genes_patriarch_01.png",
    "roundIcon": "ui_image_RoundPortrait_genes_patriarch_01.png"
  },
  {
    "id": "genesPrimus",
    "name": "Isaak",
    "title": "Primus",
    "fullName": "Isaak Starn",
    "shortName": "Isaak",
    "extraShortName": "Isaak",
    "factionId": "Genestealers",
    "alliance": "Xenos",
    "health": 70,
    "damage": 30,
    "armour": 14,
    "initialRarity": "Rare",
    "meleeDamage": "Bio",
    "meleeHits": 3,
    "rangedDamage": "Bio",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Ambush"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Blast"
    ],
    "number": 95,
    "icon": "snowprint_assets/characters/ui_image_portrait_genes_primus_01.png",
    "roundIcon": "ui_image_RoundPortrait_genes_primus_01.png"
  },
  {
    "id": "necroDestroyer",
    "name": "Imospekh",
    "title": "Hexmark Destroyer",
    "fullName": "Hexmark Destroyer Imospekh",
    "shortName": "Imospekh",
    "extraShortName": "Imospekh",
    "factionId": "Necrons",
    "alliance": "Xenos",
    "health": 72,
    "damage": 8,
    "armour": 15,
    "initialRarity": "Common",
    "meleeDamage": "Gauss",
    "meleeHits": 6,
    "rangedDamage": "Gauss",
    "rangedHits": 6,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Overwatch",
      "LivingMetal",
      "Mechanical"
    ],
    "activeAbility": [
      "Gauss"
    ],
    "passiveAbility": [],
    "number": 12,
    "icon": "snowprint_assets/characters/ui_image_portrait_necro_hexmark_01.png",
    "roundIcon": "ui_image_RoundPortrait_necro_hexmark_01.png"
  },
  {
    "id": "necroOverlord",
    "name": "Anuphet",
    "title": "Overlord",
    "fullName": "Overlord Anuphet",
    "shortName": "Anuphet",
    "extraShortName": "Anuphet",
    "factionId": "Necrons",
    "alliance": "Xenos",
    "health": 85,
    "damage": 17,
    "armour": 19,
    "initialRarity": "Epic",
    "meleeDamage": "Energy",
    "meleeHits": 4,
    "rangedDamage": "Energy",
    "rangedHits": 3,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LivingMetal",
      "Mechanical"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Energy"
    ],
    "number": 15,
    "icon": "snowprint_assets/characters/ui_image_portrait_necro_overlord_01.png",
    "roundIcon": "ui_image_RoundPortrait_necro_overlord_01.png"
  },
  {
    "id": "necroPlasmancer",
    "name": "Thutmose",
    "title": "Plasmancer",
    "fullName": "Plasmancer Thutmose",
    "shortName": "Thutmose",
    "extraShortName": "Thutmose",
    "factionId": "Necrons",
    "alliance": "Xenos",
    "health": 75,
    "damage": 30,
    "armour": 16,
    "initialRarity": "Rare",
    "meleeDamage": "Plasma",
    "meleeHits": 2,
    "rangedDamage": "Plasma",
    "rangedHits": 2,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LivingMetal",
      "Mechanical",
      "Flying"
    ],
    "activeAbility": [
      "DirectDamage"
    ],
    "passiveAbility": [
      "DirectDamage"
    ],
    "number": 14,
    "icon": "snowprint_assets/characters/ui_image_portrait_necro_plasmancer_01.png",
    "roundIcon": "ui_image_RoundPortrait_necro_plasmancer_01.png"
  },
  {
    "id": "necroSpyder",
    "name": "Aleph-Null",
    "title": "Canoptek Spyder",
    "fullName": "Canoptek Spyder Aleph-Null",
    "shortName": "Aleph-Null",
    "extraShortName": "Aleph-Null",
    "factionId": "Necrons",
    "alliance": "Xenos",
    "health": 75,
    "damage": 12,
    "armour": 22,
    "initialRarity": "Uncommon",
    "meleeDamage": "Particle",
    "meleeHits": 5,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LivingMetal",
      "Explodes",
      "Mechanical",
      "Flying",
      "Mechanic"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 13,
    "icon": "snowprint_assets/characters/ui_image_portrait_necro_spyder_01.png",
    "roundIcon": "ui_image_RoundPortrait_necro_spyder_01.png"
  },
  {
    "id": "necroWarden",
    "name": "Makhotep",
    "title": "Royal Warden",
    "fullName": "Royal Warden Makhotep",
    "shortName": "Makhotep",
    "extraShortName": "Makhotep",
    "factionId": "Necrons",
    "alliance": "Xenos",
    "health": 85,
    "damage": 18,
    "armour": 20,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Gauss",
    "rangedHits": 2,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "LivingMetal",
      "Mechanical"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 11,
    "icon": "snowprint_assets/characters/ui_image_portrait_necro_warden_01.png",
    "roundIcon": "ui_image_RoundPortrait_necro_warden_01.png"
  },
  {
    "id": "orksBigMek",
    "name": "Gibbascrapz",
    "title": "Big Mek",
    "fullName": "Gibbascrapz, da Spezulist",
    "shortName": "Gibbascrapz",
    "extraShortName": "Gibbascrapz",
    "factionId": "Orks",
    "alliance": "Xenos",
    "health": 75,
    "damage": 25,
    "armour": 30,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "GetStuckIn",
      "Mechanic"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 39,
    "icon": "snowprint_assets/characters/ui_image_portrait_orkss_mek_01.png",
    "roundIcon": "ui_image_RoundPortrait_orkss_mek_01.png"
  },
  {
    "id": "orksKillaKan",
    "name": "Snappawrecka",
    "title": "Killa Kan",
    "fullName": "Snappawrecka",
    "shortName": "Snappawrecka",
    "extraShortName": "Snappawrecka",
    "factionId": "Orks",
    "alliance": "Xenos",
    "health": 90,
    "damage": 23,
    "armour": 20,
    "initialRarity": "Uncommon",
    "meleeDamage": "Chain",
    "meleeHits": 3,
    "rangedDamage": "Projectile",
    "rangedHits": 3,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "GetStuckIn",
      "BigTarget",
      "Explodes",
      "Mechanical"
    ],
    "activeAbility": [
      "Projectile"
    ],
    "passiveAbility": [],
    "number": 40,
    "icon": "snowprint_assets/characters/ui_image_portrait_orkss_killakan_01.png",
    "roundIcon": "ui_image_RoundPortrait_orkss_killakan_01.png"
  },
  {
    "id": "orksNob",
    "name": "Tanksmasha",
    "title": "Nob on Smasha Squig",
    "fullName": "Olog Tanksmasha",
    "shortName": "Tanksmasha",
    "extraShortName": "Tanksmasha",
    "factionId": "Orks",
    "alliance": "Xenos",
    "health": 100,
    "damage": 24,
    "armour": 15,
    "initialRarity": "Epic",
    "meleeDamage": "Eviscerate",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "GetStuckIn",
      "BeastSnagga",
      "Unstoppable"
    ],
    "activeAbility": [
      "DirectDamage"
    ],
    "passiveAbility": [],
    "number": 41,
    "icon": "snowprint_assets/characters/ui_image_portrait_orkss_nob_01.png",
    "roundIcon": "ui_image_RoundPortrait_orkss_nob_01.png"
  },
  {
    "id": "orksRuntherd",
    "name": "Snotflogga",
    "title": "Runtherd",
    "fullName": "Grumbal Snotflogga",
    "shortName": "Snotflogga",
    "extraShortName": "Snotflogga",
    "factionId": "Orks",
    "alliance": "Xenos",
    "health": 120,
    "damage": 30,
    "armour": 18,
    "initialRarity": "Rare",
    "meleeDamage": "Physical",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "GetStuckIn",
      "BeastSnagga"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Physical"
    ],
    "number": 38,
    "icon": "snowprint_assets/characters/ui_image_portrait_orkss_runtherd_01.png",
    "roundIcon": "ui_image_RoundPortrait_orkss_runtherd_01.png"
  },
  {
    "id": "orksWarboss",
    "name": "Gulgortz",
    "title": "Warboss in Mega Armour",
    "fullName": "Gulgortz Bulldoza",
    "shortName": "Boss Gulgortz",
    "extraShortName": "Gulgortz",
    "factionId": "Orks",
    "alliance": "Xenos",
    "health": 100,
    "damage": 26,
    "armour": 26,
    "initialRarity": "Epic",
    "meleeDamage": "Eviscerate",
    "meleeHits": 2,
    "rangedDamage": "Projectile",
    "rangedHits": 1,
    "distance": 3,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "GetStuckIn",
      "BigTarget",
      "CrushingStrike",
      "FinalJustice",
      "Mechanical"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Projectile"
    ],
    "number": 42,
    "icon": "snowprint_assets/characters/ui_image_portrait_orkss_warboss_01.png",
    "roundIcon": "ui_image_RoundPortrait_orkss_warboss_01.png"
  },
  {
    "id": "spaceBlackmane",
    "name": "Ragnar",
    "title": "Wolf Lord of the Blackmanes",
    "fullName": "Ragnar Blackmane",
    "shortName": "Ragnar",
    "extraShortName": "Ragnar",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 100,
    "damage": 14,
    "armour": 24,
    "initialRarity": "Legendary",
    "meleeDamage": "Chain",
    "meleeHits": 7,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BeastSnagga",
      "FinalJustice",
      "RapidAssault"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 57,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_ragnar_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_ragnar_01.png"
  },
  {
    "id": "spaceHound",
    "name": "Tjark",
    "title": "Hound of Morkai Pack Leader",
    "fullName": "Tjark Wyrdslayer",
    "shortName": "Tjark",
    "extraShortName": "Tjark",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 85,
    "damage": 32,
    "armour": 23,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Infiltrate",
      "Terrifying"
    ],
    "activeAbility": [
      "Physical"
    ],
    "passiveAbility": [],
    "number": 54,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_hound_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_hound_01.png"
  },
  {
    "id": "spaceRockfist",
    "name": "Arjac",
    "title": "Champion of the Great Wolf",
    "fullName": "Arjac Rockfist",
    "shortName": "Arjac",
    "extraShortName": "Arjac",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 110,
    "damage": 23,
    "armour": 26,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Resilient",
      "TeleportStrike",
      "TerminatorArmour",
      "Unstoppable"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [],
    "number": 55,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_arjac_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_arjac_01.png"
  },
  {
    "id": "spaceStormcaller",
    "name": "Njal",
    "title": "Lord of Runes",
    "fullName": "Njal Stormcaller",
    "shortName": "Njal",
    "extraShortName": "Njal",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 80,
    "damage": 8,
    "armour": 26,
    "initialRarity": "Epic",
    "meleeDamage": "Psychic",
    "meleeHits": 3,
    "rangedDamage": "Psychic",
    "rangedHits": 2,
    "distance": 2,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "Psyker",
      "TerminatorArmour",
      "Unstoppable"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 56,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_njal_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_stormcaller_01.png"
  },
  {
    "id": "spaceWolfPriest",
    "name": "Baldr",
    "title": "Wolf Priest",
    "fullName": "Baldr Thunderbrow",
    "shortName": "Baldr",
    "extraShortName": "Baldr",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 90,
    "damage": 25,
    "armour": 21,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Healer",
      "FinalJustice",
      "Terrifying"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 124,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_wolfpriest_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_wolfpriest_01.png"
  },
  {
    "id": "spaceWulfen",
    "name": "Ulf",
    "title": "Wulfen Pack Leader",
    "fullName": "Ulf Frosthowl",
    "shortName": "Ulf",
    "extraShortName": "Ulf",
    "factionId": "SpaceWolves",
    "alliance": "Imperial",
    "health": 90,
    "damage": 33,
    "armour": 20,
    "initialRarity": "Uncommon",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "FinalJustice",
      "Unstoppable"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [
      "Power"
    ],
    "number": 53,
    "icon": "snowprint_assets/characters/ui_image_portrait_space_wulfen_01.png",
    "roundIcon": "ui_image_RoundPortrait_space_wulfen_01.png"
  },
  {
    "id": "tauAunShi",
    "name": "Aun'Shi",
    "title": "Ethereal",
    "fullName": "Aun'Shi",
    "shortName": "Aun'Shi",
    "extraShortName": "Aun'Shi",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 85,
    "damage": 13,
    "armour": 16,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 5,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 50,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_aunshi_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_aunshi_01.png"
  },
  {
    "id": "tauCrisis",
    "name": "Re'vas",
    "title": "XV8 Crisis Battlesuit",
    "fullName": "Shas'vre Vior'la Re'vas",
    "shortName": "Re'vas",
    "extraShortName": "Re'vas",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 105,
    "damage": 7,
    "armour": 25,
    "initialRarity": "Uncommon",
    "meleeDamage": "Flame",
    "meleeHits": 6,
    "rangedDamage": "Pulse",
    "rangedHits": 6,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "BigTarget",
      "Flying",
      "Mechanical",
      "RangedSpecialist"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Particle"
    ],
    "number": 49,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_crisis_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_crisis_01.png"
  },
  {
    "id": "tauDarkstrider",
    "name": "Darkstrider",
    "title": "Sub-Commander",
    "fullName": "Shas'el T'au Myamoto",
    "shortName": "Darkstrider",
    "extraShortName": "Darkstrider",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 75,
    "damage": 25,
    "armour": 17,
    "initialRarity": "Rare",
    "meleeDamage": "Physical",
    "meleeHits": 3,
    "rangedDamage": "Pulse",
    "rangedHits": 4,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Infiltrate",
      "RangedSpecialist",
      "SuppressiveFire"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 51,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_darkstrider_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_darkstrider_01.png"
  },
  {
    "id": "tauFarsight",
    "name": "Farsight",
    "title": "Hero and Traitor",
    "fullName": "Shas'o Vior'la Shovah Kais Mont'yr",
    "shortName": "Commander Farsight",
    "extraShortName": "Farsight",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 100,
    "damage": 20,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": "Plasma",
    "rangedHits": 2,
    "distance": 2,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BeastSnagga",
      "BigTarget",
      "Flying",
      "Mechanical"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 122,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_farsight_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_farsight_01.png"
  },
  {
    "id": "tauMarksman",
    "name": "Sho'syl",
    "title": "Firesight Marksman",
    "fullName": "Shas'ui Vior'la Sho'syl",
    "shortName": "Sho'syl",
    "extraShortName": "Sho'syl",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 65,
    "damage": 40,
    "armour": 16,
    "initialRarity": "Uncommon",
    "meleeDamage": "Pulse",
    "meleeHits": 1,
    "rangedDamage": "Piercing",
    "rangedHits": 1,
    "distance": 3,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Camouflage",
      "RangedSpecialist"
    ],
    "activeAbility": [
      "HeavyRound"
    ],
    "passiveAbility": [],
    "number": 48,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_marksman_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_marksman_01.png"
  },
  {
    "id": "tauShadowsun",
    "name": "Shadowsun",
    "title": "Supreme Commander of the T'au Empire",
    "fullName": "Shas'o T'au Shaserra",
    "shortName": "Commander Shadowsun",
    "extraShortName": "Shadowsun",
    "factionId": "Tau",
    "alliance": "Xenos",
    "health": 80,
    "damage": 25,
    "armour": 18,
    "initialRarity": "Legendary",
    "meleeDamage": "Blast",
    "meleeHits": 2,
    "rangedDamage": "Melta",
    "rangedHits": 2,
    "distance": 2,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Camouflage",
      "Flying",
      "Infiltrate",
      "RangedSpecialist"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [],
    "number": 52,
    "icon": "snowprint_assets/characters/ui_image_portrait_tauta_shadowsun_01.png",
    "roundIcon": "ui_image_RoundPortrait_tauta_shadowsun_01.png"
  },
  {
    "id": "templAggressor",
    "name": "Burchard",
    "title": "Aggressor Sergeant",
    "fullName": "Brother Raimund Burchard",
    "shortName": "Brother Burchard",
    "extraShortName": "Burchard",
    "factionId": "BlackTemplars",
    "alliance": "Imperial",
    "health": 120,
    "damage": 18,
    "armour": 22,
    "initialRarity": "Uncommon",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": "Bolter",
    "rangedHits": 3,
    "distance": 2,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "CrushingStrike",
      "MkXGravis",
      "SuppressiveFire"
    ],
    "activeAbility": [
      "Blast"
    ],
    "passiveAbility": [
      "Bolter"
    ],
    "number": 34,
    "icon": "snowprint_assets/characters/ui_image_portrait_templ_aggressor_01.png",
    "roundIcon": "ui_image_RoundPortrait_templ_aggressor_01.png"
  },
  {
    "id": "templAncient",
    "name": "Thoread",
    "title": "Chapter Ancient",
    "fullName": "Ancient Cantus Thoread",
    "shortName": "Ancient Thoread",
    "extraShortName": "Thoread",
    "factionId": "BlackTemplars",
    "alliance": "Imperial",
    "health": 100,
    "damage": 33,
    "armour": 22,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "FinalJustice",
      "Parry"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 36,
    "icon": "snowprint_assets/characters/ui_image_portrait_templ_ancient_01.png",
    "roundIcon": "ui_image_RoundPortrait_templ_ancient_01.png"
  },
  {
    "id": "templChampion",
    "name": "Jaeger",
    "title": "The Emperor’s Champion",
    "fullName": "Brother Kenric Jaeger",
    "shortName": "Brother Jaeger",
    "extraShortName": "Jaeger",
    "factionId": "BlackTemplars",
    "alliance": "Imperial",
    "health": 110,
    "damage": 25,
    "armour": 25,
    "initialRarity": "Epic",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "FinalJustice",
      "Parry",
      "RapidAssault"
    ],
    "activeAbility": [],
    "passiveAbility": [
      "Power"
    ],
    "number": 35,
    "icon": "snowprint_assets/characters/ui_image_portrait_templ_champion_01.png",
    "roundIcon": "ui_image_RoundPortrait_templ_champion_01.png"
  },
  {
    "id": "templHelbrecht",
    "name": "Helbrecht",
    "title": "High Marshal of the Black Templars",
    "fullName": "High Marshal Helbrecht",
    "shortName": "High Marshal Helbrecht",
    "extraShortName": "Helbrecht",
    "factionId": "BlackTemplars",
    "alliance": "Imperial",
    "health": 95,
    "damage": 15,
    "armour": 22,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 6,
    "rangedDamage": "Bolter",
    "rangedHits": 3,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "FinalJustice",
      "Parry"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 37,
    "icon": "snowprint_assets/characters/ui_image_portrait_templ_helbrecht_01.png",
    "roundIcon": "ui_image_RoundPortrait_templ_helbrecht_01.png"
  },
  {
    "id": "templSwordBrother",
    "name": "Godswyl",
    "title": "Sword Brother",
    "fullName": "Sword Brother Fedreus Godswyl",
    "shortName": "Sword Brother Godswyl",
    "extraShortName": "Godswyl",
    "factionId": "BlackTemplars",
    "alliance": "Imperial",
    "health": 95,
    "damage": 60,
    "armour": 24,
    "initialRarity": "Common",
    "meleeDamage": "Power",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Parry",
      "RapidAssault"
    ],
    "activeAbility": [
      "Power"
    ],
    "passiveAbility": [
      "Power"
    ],
    "number": 33,
    "icon": "snowprint_assets/characters/ui_image_portrait_templ_brother_01.png",
    "roundIcon": "ui_image_RoundPortrait_templ_brother_01.png"
  },
  {
    "id": "thousAhriman",
    "name": "Ahriman",
    "title": "Architect of the Rubric",
    "fullName": "Ahzek Ahriman",
    "shortName": "Ahriman",
    "extraShortName": "Ahriman",
    "factionId": "ThousandSons",
    "alliance": "Chaos",
    "health": 80,
    "damage": 30,
    "armour": 18,
    "initialRarity": "Legendary",
    "meleeDamage": "Flame",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "WeaverOfFate",
      "Flying",
      "Psyker"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 66,
    "icon": "snowprint_assets/characters/ui_image_portrait_thous_ahriman_01.png",
    "roundIcon": "ui_image_RoundPortrait_thous_ahriman_01.png"
  },
  {
    "id": "thousInfernalMaster",
    "name": "Abraxas",
    "title": "Infernal Master",
    "fullName": "Arkarzar Abraxas",
    "shortName": "Abraxas",
    "extraShortName": "Abraxas",
    "factionId": "ThousandSons",
    "alliance": "Chaos",
    "health": 70,
    "damage": 18,
    "armour": 20,
    "initialRarity": "Rare",
    "meleeDamage": "Flame",
    "meleeHits": 2,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "WeaverOfFate",
      "Psyker"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 64,
    "icon": "snowprint_assets/characters/ui_image_portrait_thous_infernal_01.png",
    "roundIcon": "ui_image_RoundPortrait_thous_infernal_01.png"
  },
  {
    "id": "thousSorcerer",
    "name": "Thaumachus",
    "title": "Exalted Sorcerer",
    "fullName": "Kairatar Thaumachus",
    "shortName": "Thaumachus",
    "extraShortName": "Thaumachus",
    "factionId": "ThousandSons",
    "alliance": "Chaos",
    "health": 75,
    "damage": 27,
    "armour": 18,
    "initialRarity": "Epic",
    "meleeDamage": "Flame",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "WeaverOfFate",
      "Flying",
      "Psyker"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 65,
    "icon": "snowprint_assets/characters/ui_image_portrait_thous_sorcerer_01.png",
    "roundIcon": "ui_image_RoundPortrait_thous_sorcerer_01.png"
  },
  {
    "id": "thousTerminator",
    "name": "Toth",
    "title": "Scarab Occult Terminator",
    "fullName": "Sokar Toth",
    "shortName": "Toth",
    "extraShortName": "Toth",
    "factionId": "ThousandSons",
    "alliance": "Chaos",
    "health": 90,
    "damage": 10,
    "armour": 27,
    "initialRarity": "Uncommon",
    "meleeDamage": "Power",
    "meleeHits": 4,
    "rangedDamage": "Flame",
    "rangedHits": 5,
    "distance": 2,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "WeaverOfFate",
      "SuppressiveFire",
      "TerminatorArmour"
    ],
    "activeAbility": [
      "HeavyRound"
    ],
    "passiveAbility": [],
    "number": 63,
    "icon": "snowprint_assets/characters/ui_image_portrait_thous_terminator_01.png",
    "roundIcon": "ui_image_RoundPortrait_thous_terminator_01.png"
  },
  {
    "id": "thousTzaangor",
    "name": "Yazaghor",
    "title": "Tzaangor Enlightened",
    "fullName": "Yazaghor Ficklefate",
    "shortName": "Yazaghor",
    "extraShortName": "Yazaghor",
    "factionId": "ThousandSons",
    "alliance": "Chaos",
    "health": 65,
    "damage": 49,
    "armour": 14,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "HeavyRound",
    "rangedHits": 1,
    "distance": 2,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "WeaverOfFate",
      "Flying"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 62,
    "icon": "snowprint_assets/characters/ui_image_portrait_thous_tzaangor_01.png",
    "roundIcon": "ui_image_RoundPortrait_thous_tzaangor_01.png"
  },
  {
    "id": "tyranDeathleaper",
    "name": "Deathleaper",
    "title": "Vanguard Organism",
    "fullName": "Deathleaper",
    "shortName": "Deathleaper",
    "extraShortName": "Deathleaper",
    "factionId": "Tyranids",
    "alliance": "Xenos",
    "health": 80,
    "damage": 24,
    "armour": 17,
    "initialRarity": "Epic",
    "meleeDamage": "Bio",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Camouflage",
      "TeleportStrike",
      "Infiltrate",
      "Terrifying"
    ],
    "activeAbility": [
      "DirectDamage"
    ],
    "passiveAbility": [],
    "number": 70,
    "icon": "snowprint_assets/characters/ui_image_portrait_tyran_deathleaper_01.png",
    "roundIcon": "ui_image_RoundPortrait_tyran_deathleaper_01.png"
  },
  {
    "id": "tyranNeurothrope",
    "name": "Neurothrope",
    "title": "Psychic Organism",
    "fullName": "Neurothrope",
    "shortName": "Neurothrope",
    "extraShortName": "Neurothrope",
    "factionId": "Tyranids",
    "alliance": "Xenos",
    "health": 85,
    "damage": 20,
    "armour": 17,
    "initialRarity": "Rare",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 3,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "RangedSpecialist",
      "Flying",
      "Psyker",
      "ShadowInTheWarp",
      "Synapse"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 67,
    "icon": "snowprint_assets/characters/ui_image_portrait_tyran_neurothrope_01.png",
    "roundIcon": "ui_image_RoundPortrait_tyran_neurothrope_01.png"
  },
  {
    "id": "tyranParasite",
    "name": "Parasite of Mortrex",
    "title": "Invader Organism",
    "fullName": "Parasite of Mortrex",
    "shortName": "Parasite of Mortrex",
    "extraShortName": "Parasite of Mortrex",
    "factionId": "Tyranids",
    "alliance": "Xenos",
    "health": 90,
    "damage": 45,
    "armour": 17,
    "initialRarity": "Epic",
    "meleeDamage": "Toxic",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Flying",
      "Synapse"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 74,
    "icon": "snowprint_assets/characters/ui_image_portrait_tyran_parasite_01.png",
    "roundIcon": "ui_image_RoundPortrait_tyran_parasite_01.png"
  },
  {
    "id": "tyranTyrantGuard",
    "name": "Tyrant Guard",
    "title": "Guardian Organism",
    "fullName": "Tyrant Guard",
    "shortName": "Tyrant Guard",
    "extraShortName": "Tyrant Guard",
    "factionId": "Tyranids",
    "alliance": "Xenos",
    "health": 125,
    "damage": 16,
    "armour": 22,
    "initialRarity": "Uncommon",
    "meleeDamage": "Piercing",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Defensive",
    "traits": [
      "BigTarget",
      "CrushingStrike"
    ],
    "activeAbility": [
      "Physical",
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 68,
    "icon": "snowprint_assets/characters/ui_image_portrait_tyran_tyrantguard_01.png",
    "roundIcon": "ui_image_RoundPortrait_tyran_tyrantguard_01.png"
  },
  {
    "id": "tyranWingedPrime",
    "name": "Winged Prime",
    "title": "Lead Warrior Organism",
    "fullName": "Winged Tyranid Prime",
    "shortName": "Winged Prime",
    "extraShortName": "Winged Prime",
    "factionId": "Tyranids",
    "alliance": "Xenos",
    "health": 100,
    "damage": 11,
    "armour": 19,
    "initialRarity": "Rare",
    "meleeDamage": "Bio",
    "meleeHits": 6,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Synapse",
      "Flying",
      "FinalJustice"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 69,
    "icon": "snowprint_assets/characters/ui_image_portrait_tyran_wingedprime_01.png",
    "roundIcon": "ui_image_RoundPortrait_tyran_wingedprime_01.png"
  },
  {
    "id": "ultraApothecary",
    "name": "Incisus",
    "title": "Apothecary",
    "fullName": "Apothecary Incisus",
    "shortName": "Incisus",
    "extraShortName": "Incisus",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 100,
    "damage": 46,
    "armour": 22,
    "initialRarity": "Common",
    "meleeDamage": "Piercing",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Healer"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 3,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_apothecary_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_apothecary_01.png"
  },
  {
    "id": "ultraCalgar",
    "name": "Calgar",
    "title": "Chapter Master",
    "fullName": "Marneus Calgar",
    "shortName": "Marneus Calgar",
    "extraShortName": "Calgar",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 95,
    "damage": 28,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Power",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "CrushingStrike",
      "FinalJustice",
      "MkXGravis"
    ],
    "activeAbility": [
      "Bolter"
    ],
    "passiveAbility": [],
    "number": 4,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_calgar_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_calgar_01.png"
  },
  {
    "id": "ultraEliminatorSgt",
    "name": "Certus",
    "title": "Eliminator Sergeant",
    "fullName": "Sergeant Certus",
    "shortName": "Certus",
    "extraShortName": "Certus",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 60,
    "damage": 55,
    "armour": 18,
    "initialRarity": "Common",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Bolter",
    "rangedHits": 1,
    "distance": 3,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Overwatch",
      "HeavyWeapon",
      "Infiltrate"
    ],
    "activeAbility": [
      "HeavyRound"
    ],
    "passiveAbility": [
      "Bolter"
    ],
    "number": 1,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_eliminator_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_eliminator_01.png"
  },
  {
    "id": "ultraInceptorSgt",
    "name": "Bellator",
    "title": "Inceptor Sergeant",
    "fullName": "Sergeant Bellator",
    "shortName": "Bellator",
    "extraShortName": "Bellator",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 85,
    "damage": 10,
    "armour": 13,
    "initialRarity": "Common",
    "meleeDamage": "Bolter",
    "meleeHits": 6,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 4,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Flying",
      "MkXGravis"
    ],
    "activeAbility": [],
    "passiveAbility": [],
    "number": 2,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_inceptor_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_inceptor_01.png"
  },
  {
    "id": "ultraTigurius",
    "name": "Tigurius",
    "title": "Chief Librarian",
    "fullName": "Varro Tigurius",
    "shortName": "Varro Tigurius",
    "extraShortName": "Tigurius",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 65,
    "damage": 30,
    "armour": 14,
    "initialRarity": "Uncommon",
    "meleeDamage": "Physical",
    "meleeHits": 1,
    "rangedDamage": "Psychic",
    "rangedHits": 1,
    "distance": 2,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "Psyker"
    ],
    "activeAbility": [
      "Psychic"
    ],
    "passiveAbility": [],
    "number": 0,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_tigurius_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_tigurius_01.png"
  },
  {
    "id": "ultraTitus",
    "name": "Titus",
    "title": "Primaris Lieutenant",
    "fullName": "Demetrian Titus",
    "shortName": "Titus",
    "extraShortName": "Titus",
    "factionId": "Ultramarines",
    "alliance": "Imperial",
    "health": 95,
    "damage": 26,
    "armour": 23,
    "initialRarity": "Epic",
    "meleeDamage": "Chain",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BeastSnagga",
      "FinalJustice"
    ],
    "activeAbility": [
      "Bolter",
      "Chain"
    ],
    "passiveAbility": [],
    "number": 90,
    "icon": "snowprint_assets/characters/ui_image_portrait_ultra_titus_01.png",
    "roundIcon": "ui_image_RoundPortrait_ultra_titus_01.png"
  },
  {
    "id": "votanIronmaster",
    "name": "Vynn",
    "title": "Brôkhyr Iron-Master",
    "fullName": "Vynn Conglahr",
    "shortName": "Vynn",
    "extraShortName": "Vynn",
    "factionId": "LeaguesOfVotann",
    "alliance": "Xenos",
    "health": 80,
    "damage": 25,
    "armour": 16,
    "initialRarity": "Rare",
    "meleeDamage": "Power",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "PrioritisedEfficiency",
      "Mechanic"
    ],
    "activeAbility": [
      "Physical"
    ],
    "passiveAbility": [],
    "number": 125,
    "icon": "snowprint_assets/characters/ui_image_portrait_votan_ironmaster_01.png",
    "roundIcon": "ui_image_RoundPortrait_votan_ironmaster_01.png"
  },
  {
    "id": "votanUthar",
    "name": "Uthar",
    "title": "High Khâl",
    "fullName": "Ûthar the Destined",
    "shortName": "Ûthar the Destined",
    "extraShortName": "Ûthar",
    "factionId": "LeaguesOfVotann",
    "alliance": "Xenos",
    "health": 90,
    "damage": 18,
    "armour": 23,
    "initialRarity": "Legendary",
    "meleeDamage": "Plasma",
    "meleeHits": 3,
    "rangedDamage": "Energy",
    "rangedHits": 3,
    "distance": 2,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "PrioritisedEfficiency",
      "Resilient"
    ],
    "activeAbility": [
      "Plasma"
    ],
    "passiveAbility": [],
    "number": 126,
    "icon": "snowprint_assets/characters/ui_image_portrait_votan_uthar_01.png",
    "roundIcon": "ui_image_RoundPortrait_votan_uthar_01.png"
  },
  {
    "id": "worldEightbound",
    "name": "Azkor",
    "title": "Exalted Eightbound",
    "fullName": "Azkor, the Eightfold",
    "shortName": "Azkor",
    "extraShortName": "Azkor",
    "factionId": "WorldEaters",
    "alliance": "Chaos",
    "health": 100,
    "damage": 24,
    "armour": 20,
    "initialRarity": "Rare",
    "meleeDamage": "Eviscerate",
    "meleeHits": 2,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BlessingsOfKhorne",
      "Daemon",
      "Resilient",
      "Terrifying",
      "Unstoppable"
    ],
    "activeAbility": [
      "Eviscerate"
    ],
    "passiveAbility": [],
    "number": 82,
    "icon": "snowprint_assets/characters/ui_image_portrait_world_eightbound_01.png",
    "roundIcon": "ui_image_RoundPortrait_world_eightbound_01.png"
  },
  {
    "id": "worldExecutions",
    "name": "Tarvakh",
    "title": "Master of Executions",
    "fullName": "Tarvakh, the Headsman ",
    "shortName": "Tarvakh",
    "extraShortName": "Tarvakh",
    "factionId": "WorldEaters",
    "alliance": "Chaos",
    "health": 95,
    "damage": 48,
    "armour": 24,
    "initialRarity": "Rare",
    "meleeDamage": "Piercing",
    "meleeHits": 1,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Crit",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BlessingsOfKhorne",
      "RapidAssault"
    ],
    "activeAbility": [
      "Piercing"
    ],
    "passiveAbility": [],
    "number": 103,
    "icon": "snowprint_assets/characters/ui_image_portrait_world_executions_01.png",
    "roundIcon": "ui_image_RoundPortrait_world_executions_01.png"
  },
  {
    "id": "worldJakhal",
    "name": "Macer",
    "title": "Jakhal Dishonoured",
    "fullName": "Macer Bloodgrin",
    "shortName": "Macer",
    "extraShortName": "Macer",
    "factionId": "WorldEaters",
    "alliance": "Chaos",
    "health": 90,
    "damage": 30,
    "armour": 10,
    "initialRarity": "Uncommon",
    "meleeDamage": "Chain",
    "meleeHits": 3,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Defensive",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BlessingsOfKhorne",
      "Resilient"
    ],
    "activeAbility": [
      "Physical"
    ],
    "passiveAbility": [],
    "number": 81,
    "icon": "snowprint_assets/characters/ui_image_portrait_world_jakhal_01.png",
    "roundIcon": "ui_image_RoundPortrait_world_jakhal_01.png"
  },
  {
    "id": "worldKharn",
    "name": "Kharn",
    "title": "Champion of Khorne",
    "fullName": "Khârn the Betrayer",
    "shortName": "Khârn",
    "extraShortName": "Khârn",
    "factionId": "WorldEaters",
    "alliance": "Chaos",
    "health": 90,
    "damage": 25,
    "armour": 20,
    "initialRarity": "Legendary",
    "meleeDamage": "Eviscerate",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 3,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Crit",
    "traits": [
      "BlessingsOfKhorne",
      "RapidAssault",
      "FinalJustice"
    ],
    "activeAbility": [
      "Eviscerate",
      "Piercing",
      "Plasma"
    ],
    "passiveAbility": [
      "Eviscerate"
    ],
    "number": 83,
    "icon": "snowprint_assets/characters/ui_image_portrait_world_kharn_01.png",
    "roundIcon": "ui_image_RoundPortrait_world_kharn_01.png"
  },
  {
    "id": "worldTerminator",
    "name": "Wrask",
    "title": "World Eaters Terminator",
    "fullName": "Wrask, the Butcher",
    "shortName": "Wrask",
    "extraShortName": "Wrask",
    "factionId": "WorldEaters",
    "alliance": "Chaos",
    "health": 95,
    "damage": 20,
    "armour": 28,
    "initialRarity": "Uncommon",
    "meleeDamage": "Flame",
    "meleeHits": 4,
    "rangedDamage": [],
    "rangedHits": 0,
    "distance": 0,
    "movement": 2,
    "equipment1": "I_Crit",
    "equipment2": "I_Block",
    "equipment3": "I_Booster_Block",
    "traits": [
      "BlessingsOfKhorne",
      "TeleportStrike",
      "RapidAssault",
      "TerminatorArmour",
      "Unstoppable"
    ],
    "activeAbility": [
      "Chain"
    ],
    "passiveAbility": [],
    "number": 80,
    "icon": "snowprint_assets/characters/ui_image_portrait_world_terminator_01.png",
    "roundIcon": "ui_image_RoundPortrait_world_terminator_01.png"
  }
] as const;
