import { Rank, Rarity } from "./enums";

export const rankToString: Record<Rank, string> = {
	[Rank.Locked]: "",
	[Rank.Stone1]: "Stone I",
	[Rank.Stone2]: "Stone II",
	[Rank.Stone3]: "Stone III",
	[Rank.Iron1]: "Iron I",
	[Rank.Iron2]: "Iron II",
	[Rank.Iron3]: "Iron III",
	[Rank.Bronze1]: "Bronze I",
	[Rank.Bronze2]: "Bronze II",
	[Rank.Bronze3]: "Bronze III",
	[Rank.Silver1]: "Silver I",
	[Rank.Silver2]: "Silver II",
	[Rank.Silver3]: "Silver III",
	[Rank.Gold1]: "Gold I",
	[Rank.Gold2]: "Gold II",
	[Rank.Gold3]: "Gold III",
	[Rank.Diamond1]: "Diamond I",
	[Rank.Diamond2]: "Diamond II",
	[Rank.Diamond3]: "Diamond III",
	[Rank.Adamantine1]: "Adamantine I",
	[Rank.Adamantine2]: "Adamantine II",
	[Rank.Adamantine3]: "Adamantine III",
};

export const rankToLevel: Record<number, number> = {
	[Rank.Locked - 1]: 0,
	[Rank.Locked]: 0,
	[Rank.Stone1]: 1,
	[Rank.Stone2]: 3,
	[Rank.Stone3]: 5,
	[Rank.Iron1]: 8,
	[Rank.Iron2]: 11,
	[Rank.Iron3]: 14,
	[Rank.Bronze1]: 17,
	[Rank.Bronze2]: 20,
	[Rank.Bronze3]: 23,
	[Rank.Silver1]: 26,
	[Rank.Silver2]: 29,
	[Rank.Silver3]: 32,
	[Rank.Gold1]: 35,
	[Rank.Gold2]: 38,
	[Rank.Gold3]: 41,
	[Rank.Diamond1]: 44,
	[Rank.Diamond2]: 47,
	[Rank.Diamond3]: 50,
	[Rank.Adamantine1]: 55,
	[Rank.Adamantine2]: 60,
	[Rank.Adamantine3]: 65,
};

export const rankToRarity: Record<number, Rarity> = {
	[Rank.Locked]: 0,
	[Rank.Stone1]: Rarity.Common,
	[Rank.Stone2]: Rarity.Common,
	[Rank.Stone3]: Rarity.Common,
	[Rank.Iron1]: Rarity.Common,
	[Rank.Iron2]: Rarity.Uncommon,
	[Rank.Iron3]: Rarity.Uncommon,
	[Rank.Bronze1]: Rarity.Uncommon,
	[Rank.Bronze2]: Rarity.Rare,
	[Rank.Bronze3]: Rarity.Rare,
	[Rank.Silver1]: Rarity.Rare,
	[Rank.Silver2]: Rarity.Epic,
	[Rank.Silver3]: Rarity.Epic,
	[Rank.Gold1]: Rarity.Epic,
	[Rank.Gold2]: Rarity.Legendary,
	[Rank.Gold3]: Rarity.Legendary,
	[Rank.Diamond1]: Rarity.Legendary,
	[Rank.Diamond2]: Rarity.Legendary,
	[Rank.Diamond3]: Rarity.Legendary,
	[Rank.Adamantine1]: Rarity.Mythic,
	[Rank.Adamantine2]: Rarity.Mythic,
	[Rank.Adamantine3]: Rarity.Mythic,
};
