import type { Alliance } from "./enums";
import { Rarity } from "./enums";

export interface IGameUnit {
	id: string;
	name: string;
	alliance: Alliance;
	faction: string;
	unitType: "character" | "mow";
	roundIcon: string;
	initialRarity: Rarity;
}

/**
 * Complete database of all game units (characters + MoWs).
 * Sourced from tacticusplanner's character and MoW data files.
 */
export const allGameUnits: IGameUnit[] = [
	// --- Characters (106) ---
	{
		id: "adeptCanoness",
		name: "Roswitha",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_adept_canoness_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "adeptCelestine",
		name: "Celestine",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_adept_celestine_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "adeptHospitaller",
		name: "Isabella",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_adept_hospitaller_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "adeptMorvenn",
		name: "Morvenn Vahl",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_adept_morvenn_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "adeptRetributor",
		name: "Vindicta",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_adept_retributor_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "admecDestroyer",
		name: "Sy-gex",
		alliance: "Imperial" as Alliance,
		faction: "AdeptusMechanicus",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_admec_destroyer_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "admecDominus",
		name: "Vitruvius",
		alliance: "Imperial" as Alliance,
		faction: "AdeptusMechanicus",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_admec_dominus_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "admecManipulus",
		name: "Actus",
		alliance: "Imperial" as Alliance,
		faction: "AdeptusMechanicus",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_admec_manipulus_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "admecMarshall",
		name: "Tan Gi'da",
		alliance: "Imperial" as Alliance,
		faction: "AdeptusMechanicus",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_admec_marshall_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "admecRuststalker",
		name: "Exitor-Rho",
		alliance: "Imperial" as Alliance,
		faction: "AdeptusMechanicus",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_admec_ruststalker_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "astraBullgryn",
		name: "Kut",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_bullgryn_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "astraCreed",
		name: "Creed",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_creed_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "astraDreir",
		name: "Dreir",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_dreir_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "astraOrdnance",
		name: "Thaddeus",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_ordnance_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "astraPrimarisPsy",
		name: "Sibyll",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_psyker_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "astraYarrick",
		name: "Yarrick",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_astra_yarrick_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "blackAbaddon",
		name: "Abaddon",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_black_abaddon_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "blackHaarken",
		name: "Haarken",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_black_haarken_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "blackObliterator",
		name: "Volk",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_black_obliterator_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "blackPossession",
		name: "Archimatos",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_black_possession_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "blackTerminator",
		name: "Angrax",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_black_terminator_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "bloodDante",
		name: "Dante",
		alliance: "Imperial" as Alliance,
		faction: "BloodAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_blood_dante_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "bloodDeathCompany",
		name: "Lucien",
		alliance: "Imperial" as Alliance,
		faction: "BloodAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_blood_deathcompany_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "bloodIntercessor",
		name: "Mataneo",
		alliance: "Imperial" as Alliance,
		faction: "BloodAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_blood_intercessor_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "bloodMephiston",
		name: "Mephiston",
		alliance: "Imperial" as Alliance,
		faction: "BloodAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_blood_mephiston_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "bloodSanguinary",
		name: "Nicodemus",
		alliance: "Imperial" as Alliance,
		faction: "BloodAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_blood_sanguinary_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "custoAtlacoya",
		name: "Atlacoya",
		alliance: "Imperial" as Alliance,
		faction: "Custodes",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_custo_atlacoya_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "custoBladeChampion",
		name: "Kariyan",
		alliance: "Imperial" as Alliance,
		faction: "Custodes",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_custo_bladechampion_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "custoKyrus",
		name: "Tyrith",
		alliance: "Imperial" as Alliance,
		faction: "Custodes",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_custo_kyrus_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "custoTrajann",
		name: "Trajann",
		alliance: "Imperial" as Alliance,
		faction: "Custodes",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_custo_trajann_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "custoVexilusPraetor",
		name: "Aesoth",
		alliance: "Imperial" as Alliance,
		faction: "Custodes",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_custo_vexilus_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "darkaAsmodai",
		name: "Asmodai",
		alliance: "Imperial" as Alliance,
		faction: "DarkAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_darka_asmodai_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "darkaAzrael",
		name: "Azrael",
		alliance: "Imperial" as Alliance,
		faction: "DarkAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_darka_azrael_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "darkaCompanion",
		name: "Forcas",
		alliance: "Imperial" as Alliance,
		faction: "DarkAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_darka_companion_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "darkaHellblaster",
		name: "Sarquael",
		alliance: "Imperial" as Alliance,
		faction: "DarkAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_darka_hellblaster_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "darkaTerminator",
		name: "Baraqiel",
		alliance: "Imperial" as Alliance,
		faction: "DarkAngels",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_darka_terminator_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "deathBlightbringer",
		name: "Corrodius",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_death_blightbringer_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "deathBlightlord",
		name: "Maladus",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_death_blightlord_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "deathPutrifier",
		name: "Pestillian",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_death_putrifier_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "deathRotbone",
		name: "Nauseous",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_death_rotbone_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "deathTyphus",
		name: "Typhus",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_death_typhus_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "eldarAutarch",
		name: "Aethana",
		alliance: "Xenos" as Alliance,
		faction: "Aeldari",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_aelda_autarch_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "eldarFarseer",
		name: "Eldryon",
		alliance: "Xenos" as Alliance,
		faction: "Aeldari",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_aelda_farseer_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "eldarJainZar",
		name: "Jain Zar",
		alliance: "Xenos" as Alliance,
		faction: "Aeldari",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_aelda_jainzar_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "eldarMauganRa",
		name: "Maugan Ra",
		alliance: "Xenos" as Alliance,
		faction: "Aeldari",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_aelda_maugan_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "eldarRanger",
		name: "Calandis",
		alliance: "Xenos" as Alliance,
		faction: "Aeldari",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_aelda_ranger_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "emperExultant",
		name: "Laviscus",
		alliance: "Chaos" as Alliance,
		faction: "EmperorsChildren",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_emper_exultant_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "emperFlawlessBlade",
		name: "Hascule",
		alliance: "Chaos" as Alliance,
		faction: "EmperorsChildren",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_emper_blade_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "emperKakophonist",
		name: "Adamatar",
		alliance: "Chaos" as Alliance,
		faction: "EmperorsChildren",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_emper_kakophonist_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "emperLucius",
		name: "Lucius",
		alliance: "Chaos" as Alliance,
		faction: "EmperorsChildren",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_emper_lucius_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "emperNoiseMarine",
		name: "Shiron",
		alliance: "Chaos" as Alliance,
		faction: "EmperorsChildren",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_emper_noisemarine_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "genesBiophagus",
		name: "Hollan",
		alliance: "Xenos" as Alliance,
		faction: "Genestealers",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_genes_biophagus_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "genesKelermorph",
		name: "Judh",
		alliance: "Xenos" as Alliance,
		faction: "Genestealers",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_genes_kelermorph_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "genesMagus",
		name: "Xybia",
		alliance: "Xenos" as Alliance,
		faction: "Genestealers",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_genes_magus_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "genesPatriarch",
		name: "The Patermine",
		alliance: "Xenos" as Alliance,
		faction: "Genestealers",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_genes_patriarch_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "genesPrimus",
		name: "Isaak",
		alliance: "Xenos" as Alliance,
		faction: "Genestealers",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_genes_primus_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "necroDestroyer",
		name: "Imospekh",
		alliance: "Xenos" as Alliance,
		faction: "Necrons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_necro_hexmark_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "necroOverlord",
		name: "Anuphet",
		alliance: "Xenos" as Alliance,
		faction: "Necrons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_necro_overlord_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "necroPlasmancer",
		name: "Thutmose",
		alliance: "Xenos" as Alliance,
		faction: "Necrons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_necro_plasmancer_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "necroSpyder",
		name: "Aleph-Null",
		alliance: "Xenos" as Alliance,
		faction: "Necrons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_necro_spyder_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "necroWarden",
		name: "Makhotep",
		alliance: "Xenos" as Alliance,
		faction: "Necrons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_necro_warden_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "orksBigMek",
		name: "Gibbascrapz",
		alliance: "Xenos" as Alliance,
		faction: "Orks",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_orkss_mek_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "orksKillaKan",
		name: "Snappawrecka",
		alliance: "Xenos" as Alliance,
		faction: "Orks",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_orkss_killakan_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "orksNob",
		name: "Tanksmasha",
		alliance: "Xenos" as Alliance,
		faction: "Orks",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_orkss_nob_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "orksRuntherd",
		name: "Snotflogga",
		alliance: "Xenos" as Alliance,
		faction: "Orks",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_orkss_runtherd_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "orksWarboss",
		name: "Gulgortz",
		alliance: "Xenos" as Alliance,
		faction: "Orks",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_orkss_warboss_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "spaceBlackmane",
		name: "Ragnar",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_ragnar_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "spaceHound",
		name: "Tjark",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_hound_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "spaceRockfist",
		name: "Arjac",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_arjac_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "spaceStormcaller",
		name: "Njal",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_stormcaller_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "spaceWolfPriest",
		name: "Baldr",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_wolfpriest_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "spaceWulfen",
		name: "Ulf",
		alliance: "Imperial" as Alliance,
		faction: "SpaceWolves",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_space_wulfen_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "tauAunShi",
		name: "Aun'Shi",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_aunshi_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "tauCrisis",
		name: "Re'vas",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_crisis_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "tauDarkstrider",
		name: "Darkstrider",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_darkstrider_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "tauFarsight",
		name: "Farsight",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_farsight_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "tauMarksman",
		name: "Sho'syl",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_marksman_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "tauShadowsun",
		name: "Shadowsun",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tauta_shadowsun_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "templAggressor",
		name: "Burchard",
		alliance: "Imperial" as Alliance,
		faction: "BlackTemplars",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_templ_aggressor_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "templAncient",
		name: "Thoread",
		alliance: "Imperial" as Alliance,
		faction: "BlackTemplars",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_templ_ancient_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "templChampion",
		name: "Jaeger",
		alliance: "Imperial" as Alliance,
		faction: "BlackTemplars",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_templ_champion_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "templHelbrecht",
		name: "Helbrecht",
		alliance: "Imperial" as Alliance,
		faction: "BlackTemplars",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_templ_helbrecht_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "templSwordBrother",
		name: "Godswyl",
		alliance: "Imperial" as Alliance,
		faction: "BlackTemplars",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_templ_brother_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "thousAhriman",
		name: "Ahriman",
		alliance: "Chaos" as Alliance,
		faction: "ThousandSons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_thous_ahriman_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "thousInfernalMaster",
		name: "Abraxas",
		alliance: "Chaos" as Alliance,
		faction: "ThousandSons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_thous_infernal_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "thousSorcerer",
		name: "Thaumachus",
		alliance: "Chaos" as Alliance,
		faction: "ThousandSons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_thous_sorcerer_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "thousTerminator",
		name: "Toth",
		alliance: "Chaos" as Alliance,
		faction: "ThousandSons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_thous_terminator_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "thousTzaangor",
		name: "Yazaghor",
		alliance: "Chaos" as Alliance,
		faction: "ThousandSons",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_thous_tzaangor_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "tyranDeathleaper",
		name: "Deathleaper",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tyran_deathleaper_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "tyranNeurothrope",
		name: "Neurothrope",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tyran_neurothrope_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "tyranParasite",
		name: "Parasite of Mortrex",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tyran_parasite_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "tyranTyrantGuard",
		name: "Tyrant Guard",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tyran_tyrantguard_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "tyranWingedPrime",
		name: "Winged Prime",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_tyran_wingedprime_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "ultraApothecary",
		name: "Incisus",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_apothecary_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "ultraCalgar",
		name: "Calgar",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_calgar_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "ultraEliminatorSgt",
		name: "Certus",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_eliminator_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "ultraInceptorSgt",
		name: "Bellator",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_inceptor_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "ultraTigurius",
		name: "Tigurius",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_tigurius_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "ultraTitus",
		name: "Titus",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_ultra_titus_01.png",
		initialRarity: Rarity.Epic,
	},
	{
		id: "votanIronmaster",
		name: "Vynn",
		alliance: "Xenos" as Alliance,
		faction: "LeaguesOfVotann",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_votan_ironmaster_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "votanUthar",
		name: "Uthar",
		alliance: "Xenos" as Alliance,
		faction: "LeaguesOfVotann",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_votan_uthar_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "worldEightbound",
		name: "Azkor",
		alliance: "Chaos" as Alliance,
		faction: "WorldEaters",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_world_eightbound_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "worldExecutions",
		name: "Tarvakh",
		alliance: "Chaos" as Alliance,
		faction: "WorldEaters",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_world_executions_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "worldJakhal",
		name: "Macer",
		alliance: "Chaos" as Alliance,
		faction: "WorldEaters",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_world_jakhal_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "worldKharn",
		name: "Kharn",
		alliance: "Chaos" as Alliance,
		faction: "WorldEaters",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_world_kharn_01.png",
		initialRarity: Rarity.Legendary,
	},
	{
		id: "worldTerminator",
		name: "Wrask",
		alliance: "Chaos" as Alliance,
		faction: "WorldEaters",
		unitType: "character",
		roundIcon: "ui_image_RoundPortrait_world_terminator_01.png",
		initialRarity: Rarity.Rare,
	},

	// --- Machines of War (7) ---
	{
		id: "astraOrdnanceBattery",
		name: "Malleus RL",
		alliance: "Imperial" as Alliance,
		faction: "AstraMilitarum",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_astra_ordnancebattery_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "blackForgefiend",
		name: "Forgefiend",
		alliance: "Chaos" as Alliance,
		faction: "BlackLegion",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_black_forgefiend_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "tyranBiovore",
		name: "Biovore",
		alliance: "Xenos" as Alliance,
		faction: "Tyranids",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_tyran_biovore_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "ultraDreadnought",
		name: "Galatian",
		alliance: "Imperial" as Alliance,
		faction: "Ultramarines",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_ultra_dreadnought_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "tauBroadside",
		name: "Tson'Ji",
		alliance: "Xenos" as Alliance,
		faction: "Tau",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_tauta_broadside_01.png",
		initialRarity: Rarity.Uncommon,
	},
	{
		id: "deathCrawler",
		name: "Plagueburst Crawler",
		alliance: "Chaos" as Alliance,
		faction: "DeathGuard",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_death_crawler_01.png",
		initialRarity: Rarity.Rare,
	},
	{
		id: "adeptExorcist",
		name: "Exorcist",
		alliance: "Imperial" as Alliance,
		faction: "Sisterhood",
		unitType: "mow",
		roundIcon: "ui_image_RoundPortrait_adept_exorcist_01.png",
		initialRarity: Rarity.Rare,
	},
];

/** Lookup map: unitId → IGameUnit */
export const unitById = new Map(allGameUnits.map((u) => [u.id, u]));

/** Sorted by name for combobox display */
export const allGameUnitsSorted = [...allGameUnits].sort((a, b) =>
	a.name.localeCompare(b.name),
);
