/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './0-routes/__root'
import { Route as SigninRouteImport } from './0-routes/signin'
import { Route as AuthenticatedRouteImport } from './0-routes/_authenticated'
import { Route as IndexRouteImport } from './0-routes/index'
import { Route as DataOnslaughtRouteImport } from './0-routes/data/onslaught'
import { Route as DataNpcsRouteImport } from './0-routes/data/npcs'
import { Route as DataEquipmentRouteImport } from './0-routes/data/equipment'
import { Route as DataCharactersRouteImport } from './0-routes/data/characters'
import { Route as AuthenticatedSettingsRouteImport } from './0-routes/_authenticated/settings'
import { Route as AuthenticatedGoalsRouteImport } from './0-routes/_authenticated/goals'
import { Route as AuthenticatedCampaignsRouteImport } from './0-routes/_authenticated/campaigns'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOnslaughtRoute = DataOnslaughtRouteImport.update({
  id: '/data/onslaught',
  path: '/data/onslaught',
  getParentRoute: () => rootRouteImport,
} as any)
const DataNpcsRoute = DataNpcsRouteImport.update({
  id: '/data/npcs',
  path: '/data/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEquipmentRoute = DataEquipmentRouteImport.update({
  id: '/data/equipment',
  path: '/data/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCharactersRoute = DataCharactersRouteImport.update({
  id: '/data/characters',
  path: '/data/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/campaigns'
    | '/goals'
    | '/settings'
    | '/data/characters'
    | '/data/equipment'
    | '/data/npcs'
    | '/data/onslaught'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/campaigns'
    | '/goals'
    | '/settings'
    | '/data/characters'
    | '/data/equipment'
    | '/data/npcs'
    | '/data/onslaught'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/_authenticated/campaigns'
    | '/_authenticated/goals'
    | '/_authenticated/settings'
    | '/data/characters'
    | '/data/equipment'
    | '/data/npcs'
    | '/data/onslaught'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  DataCharactersRoute: typeof DataCharactersRoute
  DataEquipmentRoute: typeof DataEquipmentRoute
  DataNpcsRoute: typeof DataNpcsRoute
  DataOnslaughtRoute: typeof DataOnslaughtRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/onslaught': {
      id: '/data/onslaught'
      path: '/data/onslaught'
      fullPath: '/data/onslaught'
      preLoaderRoute: typeof DataOnslaughtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/npcs': {
      id: '/data/npcs'
      path: '/data/npcs'
      fullPath: '/data/npcs'
      preLoaderRoute: typeof DataNpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/equipment': {
      id: '/data/equipment'
      path: '/data/equipment'
      fullPath: '/data/equipment'
      preLoaderRoute: typeof DataEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/characters': {
      id: '/data/characters'
      path: '/data/characters'
      fullPath: '/data/characters'
      preLoaderRoute: typeof DataCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  DataCharactersRoute: DataCharactersRoute,
  DataEquipmentRoute: DataEquipmentRoute,
  DataNpcsRoute: DataNpcsRoute,
  DataOnslaughtRoute: DataOnslaughtRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
