/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './0-routes/__root'
import { Route as SigninRouteImport } from './0-routes/signin'
import { Route as AuthenticatedRouteImport } from './0-routes/_authenticated'
import { Route as IndexRouteImport } from './0-routes/index'
import { Route as SharedRosterRouteImport } from './0-routes/shared/roster'
import { Route as DataUpgradesRouteImport } from './0-routes/data/upgrades'
import { Route as DataOnslaughtRouteImport } from './0-routes/data/onslaught'
import { Route as DataNpcsRouteImport } from './0-routes/data/npcs'
import { Route as DataMowsRouteImport } from './0-routes/data/mows'
import { Route as DataEquipmentRouteImport } from './0-routes/data/equipment'
import { Route as DataCharactersRouteImport } from './0-routes/data/characters'
import { Route as DataCampaignsRouteImport } from './0-routes/data/campaigns'
import { Route as AuthenticatedTeamsRouteImport } from './0-routes/_authenticated/teams'
import { Route as AuthenticatedSettingsRouteImport } from './0-routes/_authenticated/settings'
import { Route as AuthenticatedRosterSnapshotsRouteImport } from './0-routes/_authenticated/roster-snapshots'
import { Route as AuthenticatedRosterRouteImport } from './0-routes/_authenticated/roster'
import { Route as AuthenticatedLreRouteImport } from './0-routes/_authenticated/lre'
import { Route as AuthenticatedGwOffenseRouteImport } from './0-routes/_authenticated/gw-offense'
import { Route as AuthenticatedGoalsRouteImport } from './0-routes/_authenticated/goals'
import { Route as AuthenticatedCampaignsRouteImport } from './0-routes/_authenticated/campaigns'
import { Route as AuthenticatedCampaignProgressionRouteImport } from './0-routes/_authenticated/campaign-progression'

const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRosterRoute = SharedRosterRouteImport.update({
  id: '/shared/roster',
  path: '/shared/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const DataUpgradesRoute = DataUpgradesRouteImport.update({
  id: '/data/upgrades',
  path: '/data/upgrades',
  getParentRoute: () => rootRouteImport,
} as any)
const DataOnslaughtRoute = DataOnslaughtRouteImport.update({
  id: '/data/onslaught',
  path: '/data/onslaught',
  getParentRoute: () => rootRouteImport,
} as any)
const DataNpcsRoute = DataNpcsRouteImport.update({
  id: '/data/npcs',
  path: '/data/npcs',
  getParentRoute: () => rootRouteImport,
} as any)
const DataMowsRoute = DataMowsRouteImport.update({
  id: '/data/mows',
  path: '/data/mows',
  getParentRoute: () => rootRouteImport,
} as any)
const DataEquipmentRoute = DataEquipmentRouteImport.update({
  id: '/data/equipment',
  path: '/data/equipment',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCharactersRoute = DataCharactersRouteImport.update({
  id: '/data/characters',
  path: '/data/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const DataCampaignsRoute = DataCampaignsRouteImport.update({
  id: '/data/campaigns',
  path: '/data/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeamsRoute = AuthenticatedTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRosterSnapshotsRoute =
  AuthenticatedRosterSnapshotsRouteImport.update({
    id: '/roster-snapshots',
    path: '/roster-snapshots',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRosterRoute = AuthenticatedRosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLreRoute = AuthenticatedLreRouteImport.update({
  id: '/lre',
  path: '/lre',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGwOffenseRoute = AuthenticatedGwOffenseRouteImport.update({
  id: '/gw-offense',
  path: '/gw-offense',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGoalsRoute = AuthenticatedGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignsRoute = AuthenticatedCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCampaignProgressionRoute =
  AuthenticatedCampaignProgressionRouteImport.update({
    id: '/campaign-progression',
    path: '/campaign-progression',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/campaign-progression': typeof AuthenticatedCampaignProgressionRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/gw-offense': typeof AuthenticatedGwOffenseRoute
  '/lre': typeof AuthenticatedLreRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/roster-snapshots': typeof AuthenticatedRosterSnapshotsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/data/campaigns': typeof DataCampaignsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/mows': typeof DataMowsRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
  '/data/upgrades': typeof DataUpgradesRoute
  '/shared/roster': typeof SharedRosterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/signin': typeof SigninRoute
  '/campaign-progression': typeof AuthenticatedCampaignProgressionRoute
  '/campaigns': typeof AuthenticatedCampaignsRoute
  '/goals': typeof AuthenticatedGoalsRoute
  '/gw-offense': typeof AuthenticatedGwOffenseRoute
  '/lre': typeof AuthenticatedLreRoute
  '/roster': typeof AuthenticatedRosterRoute
  '/roster-snapshots': typeof AuthenticatedRosterSnapshotsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/teams': typeof AuthenticatedTeamsRoute
  '/data/campaigns': typeof DataCampaignsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/mows': typeof DataMowsRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
  '/data/upgrades': typeof DataUpgradesRoute
  '/shared/roster': typeof SharedRosterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/signin': typeof SigninRoute
  '/_authenticated/campaign-progression': typeof AuthenticatedCampaignProgressionRoute
  '/_authenticated/campaigns': typeof AuthenticatedCampaignsRoute
  '/_authenticated/goals': typeof AuthenticatedGoalsRoute
  '/_authenticated/gw-offense': typeof AuthenticatedGwOffenseRoute
  '/_authenticated/lre': typeof AuthenticatedLreRoute
  '/_authenticated/roster': typeof AuthenticatedRosterRoute
  '/_authenticated/roster-snapshots': typeof AuthenticatedRosterSnapshotsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/teams': typeof AuthenticatedTeamsRoute
  '/data/campaigns': typeof DataCampaignsRoute
  '/data/characters': typeof DataCharactersRoute
  '/data/equipment': typeof DataEquipmentRoute
  '/data/mows': typeof DataMowsRoute
  '/data/npcs': typeof DataNpcsRoute
  '/data/onslaught': typeof DataOnslaughtRoute
  '/data/upgrades': typeof DataUpgradesRoute
  '/shared/roster': typeof SharedRosterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/campaign-progression'
    | '/campaigns'
    | '/goals'
    | '/gw-offense'
    | '/lre'
    | '/roster'
    | '/roster-snapshots'
    | '/settings'
    | '/teams'
    | '/data/campaigns'
    | '/data/characters'
    | '/data/equipment'
    | '/data/mows'
    | '/data/npcs'
    | '/data/onslaught'
    | '/data/upgrades'
    | '/shared/roster'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/campaign-progression'
    | '/campaigns'
    | '/goals'
    | '/gw-offense'
    | '/lre'
    | '/roster'
    | '/roster-snapshots'
    | '/settings'
    | '/teams'
    | '/data/campaigns'
    | '/data/characters'
    | '/data/equipment'
    | '/data/mows'
    | '/data/npcs'
    | '/data/onslaught'
    | '/data/upgrades'
    | '/shared/roster'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/signin'
    | '/_authenticated/campaign-progression'
    | '/_authenticated/campaigns'
    | '/_authenticated/goals'
    | '/_authenticated/gw-offense'
    | '/_authenticated/lre'
    | '/_authenticated/roster'
    | '/_authenticated/roster-snapshots'
    | '/_authenticated/settings'
    | '/_authenticated/teams'
    | '/data/campaigns'
    | '/data/characters'
    | '/data/equipment'
    | '/data/mows'
    | '/data/npcs'
    | '/data/onslaught'
    | '/data/upgrades'
    | '/shared/roster'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  SigninRoute: typeof SigninRoute
  DataCampaignsRoute: typeof DataCampaignsRoute
  DataCharactersRoute: typeof DataCharactersRoute
  DataEquipmentRoute: typeof DataEquipmentRoute
  DataMowsRoute: typeof DataMowsRoute
  DataNpcsRoute: typeof DataNpcsRoute
  DataOnslaughtRoute: typeof DataOnslaughtRoute
  DataUpgradesRoute: typeof DataUpgradesRoute
  SharedRosterRoute: typeof SharedRosterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/roster': {
      id: '/shared/roster'
      path: '/shared/roster'
      fullPath: '/shared/roster'
      preLoaderRoute: typeof SharedRosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/upgrades': {
      id: '/data/upgrades'
      path: '/data/upgrades'
      fullPath: '/data/upgrades'
      preLoaderRoute: typeof DataUpgradesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/onslaught': {
      id: '/data/onslaught'
      path: '/data/onslaught'
      fullPath: '/data/onslaught'
      preLoaderRoute: typeof DataOnslaughtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/npcs': {
      id: '/data/npcs'
      path: '/data/npcs'
      fullPath: '/data/npcs'
      preLoaderRoute: typeof DataNpcsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/mows': {
      id: '/data/mows'
      path: '/data/mows'
      fullPath: '/data/mows'
      preLoaderRoute: typeof DataMowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/equipment': {
      id: '/data/equipment'
      path: '/data/equipment'
      fullPath: '/data/equipment'
      preLoaderRoute: typeof DataEquipmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/characters': {
      id: '/data/characters'
      path: '/data/characters'
      fullPath: '/data/characters'
      preLoaderRoute: typeof DataCharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/data/campaigns': {
      id: '/data/campaigns'
      path: '/data/campaigns'
      fullPath: '/data/campaigns'
      preLoaderRoute: typeof DataCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams': {
      id: '/_authenticated/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roster-snapshots': {
      id: '/_authenticated/roster-snapshots'
      path: '/roster-snapshots'
      fullPath: '/roster-snapshots'
      preLoaderRoute: typeof AuthenticatedRosterSnapshotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roster': {
      id: '/_authenticated/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof AuthenticatedRosterRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/lre': {
      id: '/_authenticated/lre'
      path: '/lre'
      fullPath: '/lre'
      preLoaderRoute: typeof AuthenticatedLreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/gw-offense': {
      id: '/_authenticated/gw-offense'
      path: '/gw-offense'
      fullPath: '/gw-offense'
      preLoaderRoute: typeof AuthenticatedGwOffenseRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/goals': {
      id: '/_authenticated/goals'
      path: '/goals'
      fullPath: '/goals'
      preLoaderRoute: typeof AuthenticatedGoalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaigns': {
      id: '/_authenticated/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AuthenticatedCampaignsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/campaign-progression': {
      id: '/_authenticated/campaign-progression'
      path: '/campaign-progression'
      fullPath: '/campaign-progression'
      preLoaderRoute: typeof AuthenticatedCampaignProgressionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedCampaignProgressionRoute: typeof AuthenticatedCampaignProgressionRoute
  AuthenticatedCampaignsRoute: typeof AuthenticatedCampaignsRoute
  AuthenticatedGoalsRoute: typeof AuthenticatedGoalsRoute
  AuthenticatedGwOffenseRoute: typeof AuthenticatedGwOffenseRoute
  AuthenticatedLreRoute: typeof AuthenticatedLreRoute
  AuthenticatedRosterRoute: typeof AuthenticatedRosterRoute
  AuthenticatedRosterSnapshotsRoute: typeof AuthenticatedRosterSnapshotsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTeamsRoute: typeof AuthenticatedTeamsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedCampaignProgressionRoute: AuthenticatedCampaignProgressionRoute,
  AuthenticatedCampaignsRoute: AuthenticatedCampaignsRoute,
  AuthenticatedGoalsRoute: AuthenticatedGoalsRoute,
  AuthenticatedGwOffenseRoute: AuthenticatedGwOffenseRoute,
  AuthenticatedLreRoute: AuthenticatedLreRoute,
  AuthenticatedRosterRoute: AuthenticatedRosterRoute,
  AuthenticatedRosterSnapshotsRoute: AuthenticatedRosterSnapshotsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTeamsRoute: AuthenticatedTeamsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  SigninRoute: SigninRoute,
  DataCampaignsRoute: DataCampaignsRoute,
  DataCharactersRoute: DataCharactersRoute,
  DataEquipmentRoute: DataEquipmentRoute,
  DataMowsRoute: DataMowsRoute,
  DataNpcsRoute: DataNpcsRoute,
  DataOnslaughtRoute: DataOnslaughtRoute,
  DataUpgradesRoute: DataUpgradesRoute,
  SharedRosterRoute: SharedRosterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
